<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_No ponsel baru Anda_newphone</name>
   <tag></tag>
   <elementGuidId>35370455-81c2-4788-a07e-d3da219b6ea9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#newphone</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='newphone']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cea79b01-96a3-4aa3-bb4f-18cc9d686adf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>a3e15234-b55a-4379-ac56-fb1186ff5be0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>NumOnly form-control input-md</value>
      <webElementGuid>4af4b4fa-c2d9-4277-96fe-5da1c89cfd25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>newphone</value>
      <webElementGuid>fb5c7595-6963-4e16-8e57-1fcf1104672e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>validateHP('e_handphone')</value>
      <webElementGuid>4ec5e62f-dbd5-4378-bb4e-689e3a629bfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>7196f113-9d43-4df8-97f6-0a0d8206554d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>899 999 9999</value>
      <webElementGuid>786eabb0-b901-4ec9-951b-f1557f825c9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>newphone</value>
      <webElementGuid>a3feb0f5-e31b-49fb-a89a-3e468b2b8283</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;newphone&quot;)</value>
      <webElementGuid>acb5ebeb-1f90-4c5e-a0b1-9b64d536c078</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='newphone']</value>
      <webElementGuid>e2026398-63e2-4392-840f-9d220ba4cd3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>72004fb7-1c85-4d71-972b-cc5302c91a35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel' and @id = 'newphone' and @placeholder = '899 999 9999' and @name = 'newphone']</value>
      <webElementGuid>02ded977-b553-4b4a-b187-91c2a0cf51c9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
