<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_No ponsel baru Anda_codeId</name>
   <tag></tag>
   <elementGuidId>4f22871b-20a3-4fe2-8d72-3d7eaf03be48</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#codeId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='codeId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8a7e50a1-9775-4caa-95c3-92bafa8b5068</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>6 Digits</value>
      <webElementGuid>720cf205-1f0b-4839-b371-09e63a2bd8d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>9738aa79-c539-4932-a345-a717403b31a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>codeId</value>
      <webElementGuid>bd06b566-2457-47f3-b943-acf654968f50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>NumOnly form-control</value>
      <webElementGuid>d037c737-2639-4777-b32e-453b3c42d706</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>15e13180-f6b2-4ef1-9719-71f0010ee3d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return isNumberKey(event)</value>
      <webElementGuid>39163c82-af44-4151-81c9-521db871305d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>codeId</value>
      <webElementGuid>ca9ee0b5-940f-40b2-97cd-2df2a1c3166c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;codeId&quot;)</value>
      <webElementGuid>ca955f75-3242-4c2c-984e-4720822d9104</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='codeId']</value>
      <webElementGuid>29532e82-e3f3-41e6-ac9e-04522793e407</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>daa16041-7fde-4cf4-9bd8-285b929d2fc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = '6 Digits' and @type = 'tel' and @id = 'codeId' and @name = 'codeId']</value>
      <webElementGuid>14ccbf95-d014-499e-a394-3f191d4f94f6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
