<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Nomor HP Minimal 8 digit</name>
   <tag></tag>
   <elementGuidId>91a5fe96-c7b1-44a8-94b6-9d297c2ed685</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#e_handphone</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='e_handphone']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4abeba9f-695f-4685-8a5d-3207db6aa266</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>e_handphone</value>
      <webElementGuid>ab4620f0-e7fd-40bf-90c4-9c2c1d40eb01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>notif</value>
      <webElementGuid>3dcfd488-f5d0-4a60-8bdf-afa3188be18a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Nomor HP Minimal 8 digit</value>
      <webElementGuid>43d5ecf9-15c6-466a-9b20-41277d710659</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;e_handphone&quot;)</value>
      <webElementGuid>46a1ca91-458f-49c0-8bd4-e1ac8681ca77</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='e_handphone']</value>
      <webElementGuid>50e202d7-5875-42c4-a6c9-3e8821482c5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='step-3']/div[5]/div/div[2]</value>
      <webElementGuid>d5886dc1-862c-4e13-8307-201b8d840ee1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No Handphone :'])[1]/following::div[5]</value>
      <webElementGuid>ca25714e-542a-46a0-89df-0b80a8ca72fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email :'])[1]/following::div[11]</value>
      <webElementGuid>cb041959-0f42-4b7e-b5b2-12fb37b7e9db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back'])[2]/preceding::div[1]</value>
      <webElementGuid>9c3709b4-5983-482f-b520-e649f414ac2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next'])[3]/preceding::div[1]</value>
      <webElementGuid>876b2906-e951-4d70-95d2-c113265f658c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Nomor HP Minimal 8 digit']/parent::*</value>
      <webElementGuid>afe422d9-4e8a-40bb-9c4e-4bf0d55b0a32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[5]/div/div[2]</value>
      <webElementGuid>572a2032-b5b7-4fbe-80a2-8f4c01f6c7a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'e_handphone' and (text() = 'Nomor HP Minimal 8 digit' or . = 'Nomor HP Minimal 8 digit')]</value>
      <webElementGuid>d3825aa3-4524-428a-ad20-6c990890383a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
