<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Format NIK Salah</name>
   <tag></tag>
   <elementGuidId>69fd53d7-e464-43fc-94b2-e45f3bd0328f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#e_idcard</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='e_idcard']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>aa68629c-f1d6-4b57-bf4f-e79e5f6219ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>e_idcard</value>
      <webElementGuid>f80a8189-611a-459b-803e-b7a8e5b873a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>notif</value>
      <webElementGuid>8692c97a-9a32-4510-8687-04ea212cbfce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Format NIK Salah</value>
      <webElementGuid>3ac06a7d-20a4-45c6-bd25-550057fee157</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;e_idcard&quot;)</value>
      <webElementGuid>0b2a89c3-5baa-44bf-a266-9c1f5398e335</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='e_idcard']</value>
      <webElementGuid>014f0c7e-45ff-4e07-97a1-0262e519e088</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='step-1']/div/div/div[2]</value>
      <webElementGuid>d5feab26-3ecf-407c-bd2b-483723597252</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NIK :'])[1]/following::div[5]</value>
      <webElementGuid>9aa87797-88e8-496b-bd3e-502c8c351a3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Identitas Pribadi'])[1]/following::div[6]</value>
      <webElementGuid>699d4776-a600-4c0c-80b1-058b0890a710</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NPWP :'])[1]/preceding::div[1]</value>
      <webElementGuid>f1e997ee-e767-4613-ba86-67790dffc5ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama :'])[1]/preceding::div[7]</value>
      <webElementGuid>974d502b-26bf-45cc-b4ee-0615cbc17310</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Format NIK Salah']/parent::*</value>
      <webElementGuid>e785d62a-cbb7-4efe-8eb8-35a19433ffb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/div/div[2]</value>
      <webElementGuid>54db94a9-5688-451f-8713-b07d5a15f6f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'e_idcard' and (text() = 'Format NIK Salah' or . = 'Format NIK Salah')]</value>
      <webElementGuid>f37ae977-cbd6-444c-9802-d084602b1b72</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
