<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Panjang karakter minimal 6, maksimal 15_4f80bf</name>
   <tag></tag>
   <elementGuidId>21bb6bf8-57e4-40f9-a023-8a4888a6cec2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#e_username</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='e_username']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ffdeb9a2-d705-42a2-9d2d-2ab13bcf3f4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>e_username</value>
      <webElementGuid>a1d958e5-d9c1-4ba9-8a7c-157910bc743a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>notif</value>
      <webElementGuid>b656af6b-63d8-48b4-a37f-78ea3b2101de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Panjang karakter minimal 6, maksimal 15 karakter.</value>
      <webElementGuid>b5d029fd-ecf1-403d-ac6e-8422b59e742a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;e_username&quot;)</value>
      <webElementGuid>0c6a3e89-d7f3-47a0-90da-2ffdf417c223</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='e_username']</value>
      <webElementGuid>51f850bc-1ee4-435f-98ec-f02c57a455d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='step-3']/div/div/div[2]</value>
      <webElementGuid>bba00b29-c144-4582-87dd-857379af4e10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Username :'])[1]/following::div[5]</value>
      <webElementGuid>dd81f163-0227-420c-b55f-be8fdbbbe8b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Informasi Akun'])[1]/following::div[6]</value>
      <webElementGuid>cc6e48ef-fd0c-4742-91c9-e401b0b1980f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password :'])[1]/preceding::div[1]</value>
      <webElementGuid>ddca0ed3-5330-44df-9a32-e6517538cb9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirm Password :'])[1]/preceding::div[10]</value>
      <webElementGuid>489e8188-6748-4ddf-98bc-6a52e6082616</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Panjang karakter minimal']/parent::*</value>
      <webElementGuid>d2c6c11c-383e-4ada-99d0-29df1df3e7b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[4]/div/div/div[2]</value>
      <webElementGuid>47251822-4bbb-417c-8b20-c2de6f6a53e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'e_username' and (text() = 'Panjang karakter minimal 6, maksimal 15 karakter.' or . = 'Panjang karakter minimal 6, maksimal 15 karakter.')]</value>
      <webElementGuid>be820d1b-6bcd-470d-845c-210bc885b41f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
