<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Username sudah terdaftar, mohon buat us_3d8c3f</name>
   <tag></tag>
   <elementGuidId>18b0206b-a2ad-42b9-9c69-2f122acff985</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#e_username</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='e_username']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3b0af5a8-cbdc-4e91-a990-099ffb941138</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>e_username</value>
      <webElementGuid>67946bc2-0b7c-4266-accf-3b5f2cae7a8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>notif</value>
      <webElementGuid>f50d900e-7314-4aff-9a80-0f40f5ccdb91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Username sudah terdaftar, mohon buat username lainUsername already used. Create another username.</value>
      <webElementGuid>99499a63-2bd9-4fb7-a4ea-94bf1590e563</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;e_username&quot;)</value>
      <webElementGuid>8c0342e1-166b-4d9a-81ad-4f348d47fe32</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='e_username']</value>
      <webElementGuid>a297a0d9-5eea-41ea-a0b0-57099a7af58c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='step-3']/div/div/div[2]</value>
      <webElementGuid>5a491fcb-fe7a-4474-b455-f5acf701c1df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Username :'])[1]/following::div[5]</value>
      <webElementGuid>16699a77-f237-4c5a-aa9a-e50a43626583</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Informasi Akun'])[1]/following::div[6]</value>
      <webElementGuid>035dd1f6-4021-4a05-ac8e-a178502bc88f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password :'])[1]/preceding::div[1]</value>
      <webElementGuid>5591968f-db99-410a-8967-d66540d51896</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Username sudah terdaftar, mohon buat username lain']/parent::*</value>
      <webElementGuid>00904b80-2622-413d-a828-612556bd1270</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[4]/div/div/div[2]</value>
      <webElementGuid>5756a947-2a38-43e9-bd44-d42f1b88c277</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'e_username' and (text() = 'Username sudah terdaftar, mohon buat username lainUsername already used. Create another username.' or . = 'Username sudah terdaftar, mohon buat username lainUsername already used. Create another username.')]</value>
      <webElementGuid>555d8a5b-258b-4794-beaf-eb17acfb9d93</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
