<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Email sudah terdaftar gunakan email lain</name>
   <tag></tag>
   <elementGuidId>f28149e3-fd2d-4e09-9185-2e55cf3b236a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#e_email</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='e_email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b83e8a04-2693-46cb-9a5a-975744dc370e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>e_email</value>
      <webElementGuid>ccecebec-d519-4777-9827-db32875e7e2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>notif</value>
      <webElementGuid>c304a780-bfac-4eca-9d4f-52b141725dc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Email sudah terdaftar gunakan email lain</value>
      <webElementGuid>0b71c194-e6c9-49be-bb17-3b0f045e76e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;e_email&quot;)</value>
      <webElementGuid>26879076-c317-4f50-97b2-5e75ec6c6993</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='e_email']</value>
      <webElementGuid>8711139b-ad42-4095-8879-5916eae01fe4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='step-3']/div[4]/div/div[2]</value>
      <webElementGuid>07ecdb13-2906-4143-96b0-b18e52a6d066</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email :'])[1]/following::div[5]</value>
      <webElementGuid>0dfbdd39-64e4-4d91-aed4-ca36b2fb950d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirm Password :'])[1]/following::div[11]</value>
      <webElementGuid>1ec8e95c-c567-4019-b77c-1e280122c3ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No Handphone :'])[1]/preceding::div[1]</value>
      <webElementGuid>e05a99f8-4dad-4018-aef4-43c3a3028be4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back'])[2]/preceding::div[7]</value>
      <webElementGuid>21a77d34-5777-45f1-926b-bf33f7d723dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Email sudah terdaftar gunakan email lain']/parent::*</value>
      <webElementGuid>19d16211-7215-4f64-a0c5-8b3a79304823</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[4]/div/div[2]</value>
      <webElementGuid>67df6e8f-83e1-4675-acae-64eafa834d88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'e_email' and (text() = 'Email sudah terdaftar gunakan email lain' or . = 'Email sudah terdaftar gunakan email lain')]</value>
      <webElementGuid>c5671893-d2af-439d-873e-f6abae57ab4e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
