<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Password_pass-graybar</name>
   <tag></tag>
   <elementGuidId>375d6e1a-6b2a-482f-81f7-c13d41a588b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.pass-graybar</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='step-3']/div[2]/div/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d9ef3143-3309-4df1-9161-9e8688901060</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pass-graybar</value>
      <webElementGuid>d5f2142c-42a8-4fc5-b5fa-0b40d248264f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;step-3&quot;)/div[@class=&quot;form-group row&quot;]/div[@class=&quot;col-sm-6&quot;]/div[@class=&quot;pass-wrapper&quot;]/div[@class=&quot;pass-graybar&quot;]</value>
      <webElementGuid>65c5b5c3-46ee-4193-a483-c83aab62f009</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='step-3']/div[2]/div/div[2]/div</value>
      <webElementGuid>cff181fb-56af-4b4e-aaeb-8bcba743c8a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password :'])[1]/following::div[6]</value>
      <webElementGuid>2cd6cc89-1bd1-46fa-b2c2-779a4c0a5b37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Username :'])[1]/following::div[12]</value>
      <webElementGuid>2d2f66b1-4094-41f5-856d-9ed6852e6d64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirm Password :'])[1]/preceding::div[3]</value>
      <webElementGuid>0a1cc9d4-c1e7-4928-afdc-266f8bf3ebb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email :'])[1]/preceding::div[9]</value>
      <webElementGuid>72cf8f41-a7bf-490e-bd3c-5e0bd3a8272a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div</value>
      <webElementGuid>f735e907-1aa8-4f0a-9c69-0a977cc3613e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
