<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Format nomor salah</name>
   <tag></tag>
   <elementGuidId>b3d4f751-7811-4376-9029-392f5d4d439b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#e_handphone</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='e_handphone']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1f8c424c-2d7b-4cc9-aeb3-cbe77b19b3cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>e_handphone</value>
      <webElementGuid>168c7538-09b7-414b-8a7c-9f25bf4ebce1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>notif</value>
      <webElementGuid>a0ff6b3a-8826-4537-bc53-5dccdca5e472</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Format nomor salah</value>
      <webElementGuid>e4cda22c-d52f-4758-9cd0-ddf4d4b003e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;e_handphone&quot;)</value>
      <webElementGuid>d4d93d19-93e8-40c7-8120-ce1c66155d99</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='e_handphone']</value>
      <webElementGuid>41237113-c2bc-48b3-b6fe-48ccadb752dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='step-3']/div[5]/div/div[2]</value>
      <webElementGuid>84bceb57-9418-48ba-bf26-4d4146f33f6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No Handphone :'])[1]/following::div[5]</value>
      <webElementGuid>7cc05f1f-00a2-450c-83af-f3bf187f0eae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email :'])[1]/following::div[11]</value>
      <webElementGuid>bc1f0e79-6ca6-4f89-a85e-cd0dcdbe0e75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back'])[2]/preceding::div[1]</value>
      <webElementGuid>0e6244da-edb1-46bf-85c8-35cafa24e95f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next'])[3]/preceding::div[1]</value>
      <webElementGuid>5f07072f-a294-4700-bb3e-911a321aab82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Format nomor salah']/parent::*</value>
      <webElementGuid>fd4a5036-c205-4a9e-a00d-a18eae4dee98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[5]/div/div[2]</value>
      <webElementGuid>da6b7df5-662d-4ad4-8d2a-5d150e90cf4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'e_handphone' and (text() = 'Format nomor salah' or . = 'Format nomor salah')]</value>
      <webElementGuid>bd223789-e8ee-4b37-8309-8313bdd9b081</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
