<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Password tidak sama</name>
   <tag></tag>
   <elementGuidId>975e4f85-0281-42e1-b85f-158813e85ae7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#e_password2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='e_password2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>04e5f162-025c-45ca-acd2-697e5b5e96bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>e_password2</value>
      <webElementGuid>238732a1-f65d-49f4-a196-0cba45222980</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>notif</value>
      <webElementGuid>8cd51074-dbd2-4c44-8180-8a0bb985eb53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Password tidak sama</value>
      <webElementGuid>e14967e3-d1fc-4df6-bf02-27bec5e59933</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;e_password2&quot;)</value>
      <webElementGuid>8d2e6337-d941-483c-9b1d-d4d4d2406586</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='e_password2']</value>
      <webElementGuid>9ee61d59-0140-4736-9d3d-8eb889ae5ab5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='step-3']/div[3]/div/div[2]</value>
      <webElementGuid>052c5b45-3bc9-44c3-a310-9590b7cff115</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirm Password :'])[1]/following::div[5]</value>
      <webElementGuid>06f0cbad-5588-4040-b45a-93c4b7cc57dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Strong password'])[1]/following::div[7]</value>
      <webElementGuid>44eb6d7b-62c9-4b1c-9f34-3c26f4f6aca3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email :'])[1]/preceding::div[1]</value>
      <webElementGuid>25559262-b34e-40f4-aa2b-56fcb8f45c8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No Handphone :'])[1]/preceding::div[7]</value>
      <webElementGuid>076284ba-5cb3-4df5-9361-f806c8dd6f58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Password tidak sama']/parent::*</value>
      <webElementGuid>ab6e95cb-b223-4ec6-a951-2e453d4bd9d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[3]/div/div[2]</value>
      <webElementGuid>469c12e2-318c-4663-a0e7-c3854633e8ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'e_password2' and (text() = 'Password tidak sama' or . = 'Password tidak sama')]</value>
      <webElementGuid>a393d4f3-82a4-4bff-9425-ebd90e6ef361</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
