<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_NIK sudah terdaftar</name>
   <tag></tag>
   <elementGuidId>b56e97a5-659a-43a6-a21c-4bacf7e4d8d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#e_idcard</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='e_idcard']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0f72924a-32c3-452d-9af8-81441a6a30e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>e_idcard</value>
      <webElementGuid>f3fd740e-18e1-4169-be53-c175ea618420</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>notif</value>
      <webElementGuid>937f58fc-1f16-45ad-b036-99b7bd675048</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>NIK sudah terdaftar  ! </value>
      <webElementGuid>88e7604d-25ac-4a45-bb8d-3a750d4cd41a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;e_idcard&quot;)</value>
      <webElementGuid>05e6a7eb-2428-4d8a-9259-43b2b65176e9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='e_idcard']</value>
      <webElementGuid>b6b363a5-effc-4824-bc71-fac6e049b60d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='step-1']/div/div/div[2]</value>
      <webElementGuid>87e94d07-ab6f-468d-8ef5-d1089527f859</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NIK :'])[1]/following::div[5]</value>
      <webElementGuid>57d1fb55-fc7d-429a-9fb0-c96ba3532fc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Identitas Pribadi'])[1]/following::div[6]</value>
      <webElementGuid>e5131a2c-893a-4e62-90e7-e3b6aaec67c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NPWP :'])[1]/preceding::div[1]</value>
      <webElementGuid>4564179d-9b3f-4c04-ae85-1ff03974a941</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama :'])[1]/preceding::div[7]</value>
      <webElementGuid>df45baf7-b5d8-4fd8-ac25-1cb31784497a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/div/div[2]</value>
      <webElementGuid>a6d05caa-21b8-44ae-ac23-04f8ce46b2cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'e_idcard' and (text() = 'NIK sudah terdaftar  ! ' or . = 'NIK sudah terdaftar  ! ')]</value>
      <webElementGuid>2e327533-7107-45cd-9a55-d6076ee6b096</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
