<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_No HP sudah terdaftar gunakan nomor lain</name>
   <tag></tag>
   <elementGuidId>5bea6582-e532-45e5-94c0-f523b82785cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#e_handphone</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='e_handphone']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>21e44d34-ab3f-4c42-b951-6f2d87c7829a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>e_handphone</value>
      <webElementGuid>68c7b21f-baba-4256-954c-c1a8fc985588</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>notif</value>
      <webElementGuid>335bf8c9-4e7b-4540-8bcf-61e05fbbe08b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>No HP sudah terdaftar gunakan nomor lain</value>
      <webElementGuid>5fed24e8-fbf1-4d15-80fd-d1ed397ea9a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;e_handphone&quot;)</value>
      <webElementGuid>6d8b2e19-d891-46cd-be23-214b253f12b9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='e_handphone']</value>
      <webElementGuid>948faa50-54a2-4c72-813e-ddb428f6fb45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='step-3']/div[5]/div/div[2]</value>
      <webElementGuid>ef069d16-a63e-4b2a-899f-8ff80a95ed23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No Handphone :'])[1]/following::div[5]</value>
      <webElementGuid>e75bbd9e-57a3-40af-828e-a9f788217cde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email :'])[1]/following::div[11]</value>
      <webElementGuid>a46962d5-5279-432e-8a98-3ded2976aace</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back'])[2]/preceding::div[1]</value>
      <webElementGuid>71e9d08a-f831-4ce9-8f45-fb1666a524c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next'])[3]/preceding::div[1]</value>
      <webElementGuid>e1f1f6e6-d608-44fe-97cc-7c5378473225</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='No HP sudah terdaftar gunakan nomor lain']/parent::*</value>
      <webElementGuid>7140ed62-001c-4ac9-b266-90c3926daffb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[5]/div/div[2]</value>
      <webElementGuid>b6b7b932-1e3e-433d-8138-3ca36d174da8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'e_handphone' and (text() = 'No HP sudah terdaftar gunakan nomor lain' or . = 'No HP sudah terdaftar gunakan nomor lain')]</value>
      <webElementGuid>3d0afb06-8aa3-44d0-adfa-d49afa179056</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
