<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Next</name>
   <tag></tag>
   <elementGuidId>985dbc6d-07f7-4014-a573-edb7bf68117d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#step-1 > div.col.text-center</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='step-1']/div[7]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>420ab9d1-2f28-4226-ba94-2aa72ac94784</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col text-center</value>
      <webElementGuid>48e6360a-b913-4f6c-8bea-0728824e22ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>                  	 
                     Next
                  </value>
      <webElementGuid>a5a80b1b-1931-4360-ab5d-448c84c36123</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;step-1&quot;)/div[@class=&quot;col text-center&quot;]</value>
      <webElementGuid>6abb2cfe-f2f4-46d7-a123-96da60d64528</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='step-1']/div[7]</value>
      <webElementGuid>791ee1b5-20f8-464a-92d2-ab9029193153</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tanggal Lahir :'])[1]/following::div[2]</value>
      <webElementGuid>08a7040d-8df9-4103-bdc8-480d057938c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jenis Kelamin :'])[1]/following::div[4]</value>
      <webElementGuid>f0b08c42-f70a-4c6f-9cb5-734ee30bc73b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alamat EKTP'])[1]/preceding::div[1]</value>
      <webElementGuid>a7f13827-8a5e-4d88-a084-d5b60e34d264</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[7]</value>
      <webElementGuid>c16bf829-a14f-4721-8903-532040671607</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '                  	 
                     Next
                  ' or . = '                  	 
                     Next
                  ')]</value>
      <webElementGuid>6d72abfc-7b38-4970-924d-ca8033856139</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
