<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Harus 16 Digit</name>
   <tag></tag>
   <elementGuidId>2bf04fd5-d0a2-4158-9a48-75facca35871</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#e_idcard</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='e_idcard']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a307e99e-381e-4e20-a08a-945307fde484</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>e_idcard</value>
      <webElementGuid>96bf2d1c-4598-4d91-9620-f3c6cda72268</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>notif</value>
      <webElementGuid>c5c04f31-311b-4c02-af2f-0ba977ebfa38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Harus 16 Digit.</value>
      <webElementGuid>5f2601b0-b4a9-42b9-8dfd-55fa6a8e95d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;e_idcard&quot;)</value>
      <webElementGuid>c4ed6884-155c-4226-a452-a35a055852a0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='e_idcard']</value>
      <webElementGuid>40967a18-bd8d-478d-85e9-5fd5f8619bde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='step-1']/div/div/div[2]</value>
      <webElementGuid>8bf5b5ab-183d-41a4-b62c-f7cfe91e917b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NIK :'])[1]/following::div[5]</value>
      <webElementGuid>1d32f272-2f7b-45a1-9f4c-ce6248a5b82f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Identitas Pribadi'])[1]/following::div[6]</value>
      <webElementGuid>fd15dbf9-01ac-4538-bf2d-476e65d3a52f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NPWP :'])[1]/preceding::div[1]</value>
      <webElementGuid>294ed8d5-b791-41dc-836c-350a1992c717</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama :'])[1]/preceding::div[7]</value>
      <webElementGuid>7fecce4b-9a30-402d-a08d-48418df19681</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Harus']/parent::*</value>
      <webElementGuid>044bd8ba-3799-4f82-b9aa-fa64e3b86a1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/div/div[2]</value>
      <webElementGuid>5d1ddadb-a46d-44fb-97e1-2c0da43aba93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'e_idcard' and (text() = 'Harus 16 Digit.' or . = 'Harus 16 Digit.')]</value>
      <webElementGuid>b0a48a63-10a1-46d9-a3a8-e8a0e39f28bc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
