<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_NIK_input-group mb-2</name>
   <tag></tag>
   <elementGuidId>488c2b17-22cf-4912-bff4-b59e3d1c2ca2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.input-group.mb-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='step-1']/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e016dae5-373d-4964-abc0-344911ffd45d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-group mb-2</value>
      <webElementGuid>0dc77780-3b6b-4fd3-8f32-a93501c027c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;step-1&quot;)/div[@class=&quot;form-group row&quot;]/div[@class=&quot;col-sm-6&quot;]/div[@class=&quot;input-group mb-2&quot;]</value>
      <webElementGuid>66946706-281a-40e4-b663-5889b2cabbf2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='step-1']/div/div/div</value>
      <webElementGuid>3250f337-effc-4219-8b02-f3c9e5519777</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NIK :'])[1]/following::div[2]</value>
      <webElementGuid>d935d90a-1e4f-49bb-a54e-f93db6c00201</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Identitas Pribadi'])[1]/following::div[3]</value>
      <webElementGuid>f74547d0-b9ff-462a-a491-7f0d8139a69b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NPWP :'])[1]/preceding::div[4]</value>
      <webElementGuid>b99c53eb-4d66-4c62-9eb8-1aa03c000ff2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama :'])[1]/preceding::div[10]</value>
      <webElementGuid>c09992c7-cfe8-42e6-9af2-d733a294203c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/div/div</value>
      <webElementGuid>d9efb617-2538-4e4e-860a-49546d2437ce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
