<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h3_Foto dan Tandatangan</name>
   <tag></tag>
   <elementGuidId>469ee713-72a7-48d8-bde7-78c757883608</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#step-4 > h3.card-title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='step-4']/h3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>32286fc4-9046-4e37-9936-d7a988cf341d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-title</value>
      <webElementGuid>86e54fb5-d9d4-4d78-b881-fe8fbc29d075</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Foto dan Tandatangan</value>
      <webElementGuid>42f41960-9533-4448-a151-75017e169c3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;step-4&quot;)/h3[@class=&quot;card-title&quot;]</value>
      <webElementGuid>68d88688-1963-4320-8e5d-ce180c1cb118</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='step-4']/h3</value>
      <webElementGuid>96bc8f80-82da-4250-bb3b-fdc85fac2c44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next'])[3]/following::h3[1]</value>
      <webElementGuid>06184e73-db92-4099-82ac-5f48a819a5a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back'])[2]/following::h3[1]</value>
      <webElementGuid>8dec0df4-7a7b-4388-a4c0-a0a2a515f89d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Foto E-KTP :'])[1]/preceding::h3[1]</value>
      <webElementGuid>c770d395-fc0e-44df-85b7-bcb83aaa2ac2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Plih File Foto E-KTP'])[1]/preceding::h3[1]</value>
      <webElementGuid>760dbfed-52b9-41ba-a987-2dd0610e22be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Foto dan Tandatangan']/parent::*</value>
      <webElementGuid>ce9b5fd6-10e1-4d5d-bb95-613679fd7fc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/h3</value>
      <webElementGuid>33c9e9b0-8f3c-488b-b556-632ed0fca292</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[(text() = 'Foto dan Tandatangan' or . = 'Foto dan Tandatangan')]</value>
      <webElementGuid>821ca9e9-542e-4b5e-8ddc-02120ae54522</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
