<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h3_Informasi Akun</name>
   <tag></tag>
   <elementGuidId>a114d497-40f7-4b2f-9c28-7a038391b699</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#step-3 > h3.card-title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='step-3']/h3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>f45f0798-b4fc-4524-8bce-e1a333c41b9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-title</value>
      <webElementGuid>9d2f60ca-e63d-45ab-930d-fe55ce0ec56d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Informasi Akun</value>
      <webElementGuid>83eae40f-d771-4673-a40e-291ecd8d3655</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;step-3&quot;)/h3[@class=&quot;card-title&quot;]</value>
      <webElementGuid>1a8678e5-c0a8-4b88-9f01-f3bebbd27b32</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='step-3']/h3</value>
      <webElementGuid>67958a80-84d0-4899-8938-aa677977240b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next'])[2]/following::h3[1]</value>
      <webElementGuid>507d143f-dd53-479d-a4e3-74494b4a0aef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back'])[1]/following::h3[1]</value>
      <webElementGuid>4e0987cb-d62f-41e7-9ff2-c2d5ad427a12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Username :'])[1]/preceding::h3[1]</value>
      <webElementGuid>695e0352-961b-491f-839b-64b1c1deda26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password :'])[1]/preceding::h3[1]</value>
      <webElementGuid>a2503382-fac3-4a0a-bcd6-3acb4881859c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Informasi Akun']/parent::*</value>
      <webElementGuid>4c2f1ada-15cc-421a-99f3-9536fbdf414d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/h3</value>
      <webElementGuid>7169eaf8-0bf5-46e5-899a-5e41996042e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[(text() = 'Informasi Akun' or . = 'Informasi Akun')]</value>
      <webElementGuid>5a3b08a7-d3bb-4320-81a7-81073aee0072</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
