<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tempat Lahir_lbrith</name>
   <tag></tag>
   <elementGuidId>732e599b-c032-443e-ab89-02b3c3de1140</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lbrith</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='lbrith']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>84376872-0105-447e-b491-a92dfa27d997</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a2614193-1047-41a6-90b7-edbebce0e48b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-md</value>
      <webElementGuid>6da1498b-508a-4163-8e9a-d3aa2e79e8ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lbrith</value>
      <webElementGuid>8acec64a-9e8c-4efc-90a7-cb95edb66972</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>ab34017a-681c-494e-857d-8b265bc072fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>validatebriths('e_lbrith',this)</value>
      <webElementGuid>01818d03-7db7-4e4a-9f7b-de943e455d4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>lbrith</value>
      <webElementGuid>6b241a4c-e28b-46b0-a277-4031d4152d90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lbrith&quot;)</value>
      <webElementGuid>1e22460f-74f2-4be5-a8ca-6d294169479b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='lbrith']</value>
      <webElementGuid>543d4efe-ecfd-40d7-9e8c-7724cd8de6fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='step-1']/div[4]/div/div/input</value>
      <webElementGuid>188cef20-650d-49ec-bd9a-5e1ce028f52d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/input</value>
      <webElementGuid>8aed2a29-0939-43a9-bdf2-b1d7f7ed517c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'lbrith' and @name = 'lbrith']</value>
      <webElementGuid>ba0b8425-5f13-4f9c-abd4-f30c2786d907</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
