<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_No Handphone_handphone</name>
   <tag></tag>
   <elementGuidId>f6e8e4e9-238d-46c3-8383-ecc5fad32d2d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#handphone</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='handphone']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>65e338bf-0f0a-4142-af31-711c38cc204b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>ec71b10e-2573-42fb-b315-b3416007b8ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>NumOnly form-control input-md</value>
      <webElementGuid>d290cf8a-d66a-48fd-a514-50e3c5fd3656</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>handphone</value>
      <webElementGuid>ce6318f6-2a8a-4500-8e03-18a615da2e8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>validateHP('e_handphone')</value>
      <webElementGuid>4e7a4274-60f9-47e5-b19d-d4b8402260e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>ab8eb927-5efa-4854-b8c7-c9f2a1c7551d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>812 345 6789</value>
      <webElementGuid>60889638-049d-4796-b0de-9f8689bcfb9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>handphone</value>
      <webElementGuid>12acd4e5-592f-4c42-a3c4-fdbe92c05dcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;handphone&quot;)</value>
      <webElementGuid>bc282ad5-1b0c-46bb-b568-addd7b25dbec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='handphone']</value>
      <webElementGuid>e4b36819-6529-4936-98df-69407373e06c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='step-3']/div[5]/div/div/input</value>
      <webElementGuid>0f010718-d653-44c7-930f-bfeb84e8ea4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[5]/div/div/input</value>
      <webElementGuid>6b1409cc-6d72-441b-aa86-efee0892c5a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel' and @id = 'handphone' and @placeholder = '812 345 6789' and @name = 'handphone']</value>
      <webElementGuid>c7ec64db-cdd9-4e9b-b967-453b7b5ccabd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
