<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Laki-laki                           _9d22b4</name>
   <tag></tag>
   <elementGuidId>b56480f1-e149-4691-a4d2-8629553c2601</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#jk</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='jk']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>17457623-2b1d-4a47-8f80-73394dfd7e76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>jk</value>
      <webElementGuid>a127e1cf-51fa-4338-affc-2decfb6b19d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>jk</value>
      <webElementGuid>cc0f9cb7-3d72-40f8-b592-261ff6dfc68b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dateselect</value>
      <webElementGuid>27668681-fa3b-4f50-934d-707617e8f2dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                           Laki-laki
                           Perempuan
                        </value>
      <webElementGuid>1b4b44b1-1f32-4045-a1a8-0eaa0191f73c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jk&quot;)</value>
      <webElementGuid>143ce101-9f04-430e-b19e-65252eaa6004</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='jk']</value>
      <webElementGuid>93c2f0b0-d95a-4306-8155-fa3a852de17d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='step-1']/div[5]/div/select</value>
      <webElementGuid>2a132490-461d-467f-baab-bc7c88cb92ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jenis Kelamin :'])[1]/following::select[1]</value>
      <webElementGuid>f8cf6e65-11eb-448a-9c7b-5dd9af3f10bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tempat Lahir :'])[1]/following::select[1]</value>
      <webElementGuid>c4a5be6c-d5f3-4e4f-ac57-ca33fe5cf2c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tanggal Lahir :'])[1]/preceding::select[1]</value>
      <webElementGuid>d625c4dd-a7fa-4dbc-8a6c-350e63265b01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next'])[1]/preceding::select[4]</value>
      <webElementGuid>dd8eef92-555e-436b-a9ef-a4941150ea03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>44f7b7e6-0272-4475-8c4b-ba19a5f04e73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'jk' and @id = 'jk' and (text() = '
                           Laki-laki
                           Perempuan
                        ' or . = '
                           Laki-laki
                           Perempuan
                        ')]</value>
      <webElementGuid>4f288ada-13a0-4531-85f8-8a6b744dba8a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
