<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Jan                           Feb   _9011ea</name>
   <tag></tag>
   <elementGuidId>7439d39c-40aa-4fae-9499-1c31128829a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Month</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='Month']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>6bf8d244-c603-4e26-a17a-16bc4fd45575</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>month dateselect mr-2</value>
      <webElementGuid>b9e985c8-3ab7-4912-aa1a-08f275154a09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dobMonth</value>
      <webElementGuid>5bed9a3b-2b09-4c41-81d8-50189541ece5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Month</value>
      <webElementGuid>6453a94b-4fb2-4709-a062-94dc90d333f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                           Jan
                           Feb
                           Mar
                           Apr
                           Mei
                           Jun
                           Jul
                           Ags
                           Sep
                           Okt
                           Nov
                           Des
                        </value>
      <webElementGuid>3aa616bd-c0dd-42af-9089-f5af885e6249</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Month&quot;)</value>
      <webElementGuid>414e0726-9bb5-493f-b55c-19dbed0c40b8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='Month']</value>
      <webElementGuid>6f7ea861-ba08-4056-b572-2647801b9782</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='step-1']/div[6]/div/select[2]</value>
      <webElementGuid>5aa9eba8-e4f4-4da7-94db-40e00fb83c38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tanggal Lahir :'])[1]/following::select[2]</value>
      <webElementGuid>f36c6040-bc47-4403-b6a5-5ee743d82be3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jenis Kelamin :'])[1]/following::select[3]</value>
      <webElementGuid>2eaf2ce8-6b00-46b9-a8bc-454612b2c297</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next'])[1]/preceding::select[2]</value>
      <webElementGuid>9b74780a-1a2f-4cff-aaad-5ea9a119df4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alamat EKTP'])[1]/preceding::select[2]</value>
      <webElementGuid>705cb86d-0a47-4f87-97fc-159139cf6c60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select[2]</value>
      <webElementGuid>0a7296b2-4bd1-46d0-9ec2-aaf70661053d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'dobMonth' and @id = 'Month' and (text() = '
                           Jan
                           Feb
                           Mar
                           Apr
                           Mei
                           Jun
                           Jul
                           Ags
                           Sep
                           Okt
                           Nov
                           Des
                        ' or . = '
                           Jan
                           Feb
                           Mar
                           Apr
                           Mei
                           Jun
                           Jul
                           Ags
                           Sep
                           Okt
                           Nov
                           Des
                        ')]</value>
      <webElementGuid>6956aa64-345c-42dc-9537-a6347e95e027</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
