<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Password harus mengandung minimal 1 Si_3e88b9</name>
   <tag></tag>
   <elementGuidId>33143353-3ea3-4411-a1e8-a5da63e4b41d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.pass-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='step-3']/div[2]/div/div[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>89a56de4-6a17-4872-8e7e-317b3ca5a93d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pass-text</value>
      <webElementGuid>60402c9f-38e9-477a-acfd-c61f980ef3ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Password harus mengandung minimal 1 Simbol/Karakter Spesial</value>
      <webElementGuid>5c7e2c2c-7419-4304-b27e-3f3524ef1c8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;step-3&quot;)/div[@class=&quot;form-group row has-error has-feedback&quot;]/div[@class=&quot;col-sm-6&quot;]/div[@class=&quot;pass-wrapper&quot;]/span[@class=&quot;pass-text&quot;]</value>
      <webElementGuid>f456d3bb-fe8e-4976-8e4f-611efd9cb401</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='step-3']/div[2]/div/div[2]/span</value>
      <webElementGuid>d1b46c62-d017-4c40-8971-f9cac6f14b0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password :'])[1]/following::span[1]</value>
      <webElementGuid>02d9a5d7-2483-4893-b1d0-63e4248cd3e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Username :'])[1]/following::span[1]</value>
      <webElementGuid>011fd539-41bf-4062-aaa5-a7ec5f4eb9cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirm Password :'])[1]/preceding::span[1]</value>
      <webElementGuid>bfbfe0ad-2c80-47fa-99b6-4878609bfef8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email :'])[1]/preceding::span[1]</value>
      <webElementGuid>d3084e3e-7db2-4328-bc19-772aa25be357</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Password harus mengandung minimal 1 Simbol/Karakter Spesial']/parent::*</value>
      <webElementGuid>48fdd060-b891-4f6d-a08f-8a50714a7343</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span</value>
      <webElementGuid>a0665e66-4395-4dc8-ba8e-ef4b67d1416a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Password harus mengandung minimal 1 Simbol/Karakter Spesial' or . = 'Password harus mengandung minimal 1 Simbol/Karakter Spesial')]</value>
      <webElementGuid>d7f6c45b-de09-4150-891b-4d6256cc011e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
