<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Masukkan kode OTP_codeEm</name>
   <tag></tag>
   <elementGuidId>c1d488b7-0096-4fab-941f-d11968ff1d64</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#codeEm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='codeEm']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a8a650ce-a881-4c81-a507-34c095b000af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>6 Digits</value>
      <webElementGuid>10f1e314-d544-4fe3-b213-6d972723d667</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>codeEm</value>
      <webElementGuid>4654528a-def0-4c13-b013-df6a5eee77ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>NumOnly form-control</value>
      <webElementGuid>eef29bc9-ee55-416d-b027-e17cb2c5de32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>b3b565d0-ad2d-4ced-93d1-c759c87d3027</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>codeEm</value>
      <webElementGuid>915e0872-9c69-487a-96a7-1a316a2e6ba1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>2f99aa2d-fd62-48be-8efb-e2c0dc58eb40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;codeEm&quot;)</value>
      <webElementGuid>3b4d3ddb-6ef9-4ff9-8518-c75ce81579bb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='codeEm']</value>
      <webElementGuid>13bbdc87-9c65-425d-9ab4-b82846299342</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tmail']/div/div/div/div/form/div[4]/div/div/input[3]</value>
      <webElementGuid>e7e9598d-a7c3-46e3-a4c2-0f0feb6e456b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/div/div/div/div/form/div[4]/div/div/input[3]</value>
      <webElementGuid>7ac67a84-67d8-492b-b001-2d181cdb820a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = '6 Digits' and @id = 'codeEm' and @name = 'codeEm' and @type = 'tel']</value>
      <webElementGuid>88446ecf-ae16-4c44-b878-fcd3ae65fa0c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
