<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Masukkan kode OTP_codeId</name>
   <tag></tag>
   <elementGuidId>e48dda1a-ed29-4ebb-bad2-1805de99c0b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#codeId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='codeId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8ddefed8-1c4c-48d8-a017-b34a36bfb88a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>6 Digits</value>
      <webElementGuid>0310c759-b8a5-4026-bdbd-9960f8c2afc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>codeId</value>
      <webElementGuid>978023ad-f723-49ee-a941-fc3ac1d63334</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>NumOnly form-control</value>
      <webElementGuid>10bbd934-d89d-4d9a-b2d0-2794faea56f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>219d6b6a-0338-4f70-bd49-c0a746f54d46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>aa85e60f-d72d-4c02-ab7b-e28ab231c8fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>codeId</value>
      <webElementGuid>4632c53a-673d-49b9-9f26-a91c4aa69c11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;codeId&quot;)</value>
      <webElementGuid>3c2ec3fb-6a85-4b0d-ac20-db48c6f96f71</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='codeId']</value>
      <webElementGuid>875aaabc-e0c2-415a-8765-a5aa058aeffa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tsms']/div/div/div/div/form/div[4]/div/div/input[3]</value>
      <webElementGuid>d2125872-9b5b-47f7-98c5-b4a652f00aab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[3]</value>
      <webElementGuid>c981106c-30be-4592-80d1-fa3ac67fe0ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = '6 Digits' and @id = 'codeId' and @type = 'tel' and @name = 'codeId']</value>
      <webElementGuid>33fd3462-d11e-40b8-b62d-c3cc5af9dd63</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
