<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Lanjutkan</name>
   <tag></tag>
   <elementGuidId>cc1b915c-a7e3-4219-bfb4-6d87f0f7fb6e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='detail_doc']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#detail_doc</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9b7e21c7-c490-4c91-a520-175a7734715b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btns btn-primary nextBtn</value>
      <webElementGuid>ff683bc4-134e-4bf9-a3eb-f289b3347f83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>detail_doc</value>
      <webElementGuid>39aa992f-794a-4e98-a4e1-36499f4c9b30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Lanjutkan </value>
      <webElementGuid>dbe0579a-a630-4753-849b-5116ad31aeab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;detail_doc&quot;)</value>
      <webElementGuid>57a38750-2760-4033-9f39-cce41bc647aa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='detail_doc']</value>
      <webElementGuid>178705dd-151a-4942-92f9-76b546762b21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kembali'])[1]/following::button[1]</value>
      <webElementGuid>2d156b4b-7e64-46c5-82c4-ac91a26f78ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tambah Penerima'])[1]/following::button[2]</value>
      <webElementGuid>10dc23c8-3ba3-411f-a8a7-9a1ca1e693e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fri, Dec 09'])[1]/preceding::button[1]</value>
      <webElementGuid>be883c21-11fe-43b3-b650-9442cbf1eaaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='event'])[2]/preceding::button[1]</value>
      <webElementGuid>4806f74a-b448-4fb7-8807-7d82f8a85402</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Lanjutkan']/parent::*</value>
      <webElementGuid>57bcc32e-4f29-47c6-9e0c-1c066d6e822d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/button[2]</value>
      <webElementGuid>7e879ece-f64f-4e2e-bc0f-d9692b205abb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'detail_doc' and (text() = ' Lanjutkan ' or . = ' Lanjutkan ')]</value>
      <webElementGuid>f37cad91-5b48-4a1a-90d7-4cdc402e4246</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
