<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Paraf_lockinit1</name>
   <tag></tag>
   <elementGuidId>e67fd774-b15f-4940-8803-c54e65fe5e97</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lockinit1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='lockinit1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>274a2536-a870-4b9d-9a57-c375a3f9d80f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lockinit1</value>
      <webElementGuid>d2ca1982-e24d-4937-909f-9996f51a551a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-warning lockinit</value>
      <webElementGuid>630021e9-88fe-412d-998f-e199dd4ccccf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lockinit1&quot;)</value>
      <webElementGuid>1c32ad0b-ee6c-42b8-8a06-19804c685428</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='lockinit1']</value>
      <webElementGuid>1246f616-0be5-4e27-8f7b-f4a3d8c75fab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='widgetlockinit1']/button</value>
      <webElementGuid>31ed05e7-46da-495e-bf09-ed4010b54d17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Paraf'])[1]/following::button[1]</value>
      <webElementGuid>7d1bffd2-f74e-4022-9b14-468b571e92a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading page ...'])[1]/preceding::button[2]</value>
      <webElementGuid>4a2950f8-c9d6-420e-979d-7b97c063c2e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kembali'])[1]/preceding::button[2]</value>
      <webElementGuid>9aa047f3-006a-4531-bcb8-518d732b300e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/div/div[2]/div/div/button</value>
      <webElementGuid>794461af-a9e6-445d-b9a4-c11f9af584fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'lockinit1']</value>
      <webElementGuid>dd1ff93d-1957-4629-a6c9-4fab0d01a98a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
