<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Info</name>
   <tag></tag>
   <elementGuidId>d4632acc-dade-47e7-ab36-23295babca09</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#goInfo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='goInfo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>81d100bd-5d46-4236-b90a-4189a84c1cf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-light mt-2 mb-2 text-dark</value>
      <webElementGuid>f73f5968-d98f-4cd6-854c-d777ca8b093b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>goInfo</value>
      <webElementGuid>063a6152-aaf6-480c-8f6e-cbe5401a5420</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
				  Info
				</value>
      <webElementGuid>77e7ad72-571e-442a-b67a-116d41fdb850</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;goInfo&quot;)</value>
      <webElementGuid>f88a4db3-f2f7-478d-b6c6-b55af7010a7d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='goInfo']</value>
      <webElementGuid>962516ee-7bb4-41bc-a039-43553c9a3f8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hdr']/div/div[2]/button[2]</value>
      <webElementGuid>07bfe333-1e86-4e57-b475-2ff7bce80111</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading page ...'])[1]/preceding::button[1]</value>
      <webElementGuid>fb854b49-bb5a-4337-91a2-35d16da3d87d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kembali'])[1]/preceding::button[1]</value>
      <webElementGuid>7909a62e-5084-4434-9c0d-4078f108fdcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Info']/parent::*</value>
      <webElementGuid>a60769e9-120e-467e-a7d5-d6b45f2ae6a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button[2]</value>
      <webElementGuid>0707dea2-0127-4f38-b283-99c39dd9e777</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'goInfo' and (text() = '
				  Info
				' or . = '
				  Info
				')]</value>
      <webElementGuid>aca57033-808a-4123-b702-0cfa50537536</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
