<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Paraf_lockinit1</name>
   <tag></tag>
   <elementGuidId>e67fd774-b15f-4940-8803-c54e65fe5e97</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='lockinit1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#lockinit1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0f76df7b-883a-40a8-8ff1-bd328cba0d30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lockinit1</value>
      <webElementGuid>7b310afc-96f7-4570-aab7-aea46555872e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-warning lockinit</value>
      <webElementGuid>c0ab2956-c7c3-4535-8632-4924a4f9e724</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lockinit1&quot;)</value>
      <webElementGuid>d76788c6-031d-4ff7-84e2-570686ae0915</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='lockinit1']</value>
      <webElementGuid>18601d5d-4467-45e5-8b1b-ec27db53df34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='widgetlockinit1']/button</value>
      <webElementGuid>210a2b39-fe3f-4188-8ff1-b1a05487eb84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Paraf'])[1]/following::button[1]</value>
      <webElementGuid>26eb63b2-5363-4d71-98e0-9714d67fef06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading page ...'])[1]/preceding::button[2]</value>
      <webElementGuid>9b3a27b5-2271-4dd3-86eb-948c22c61b31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kembali'])[1]/preceding::button[2]</value>
      <webElementGuid>98ab1928-b9fe-47f0-a4a4-4793441d1486</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/div/div[2]/div/div/button</value>
      <webElementGuid>b2f26a40-222c-404f-9a41-0e718ffe6c5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'lockinit1']</value>
      <webElementGuid>80ed508b-3e5d-44d2-b749-63b7f0421e8e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
