<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Proses</name>
   <tag></tag>
   <elementGuidId>e687bbbf-6176-489d-a292-46d4dbe0eb69</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='pros']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#pros</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c90f9902-7629-4ed1-b86f-b6302cca873e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5714cdcd-7461-4289-9a20-2eba92558f88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success</value>
      <webElementGuid>11d137ce-f199-4027-b12f-ad352d704202</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pros</value>
      <webElementGuid>fe1d9c31-a60b-4ad4-ab7d-24e40eb90d73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Proses  </value>
      <webElementGuid>f988a097-64f5-4e1a-a45e-6d1c5ca2207b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pros&quot;)</value>
      <webElementGuid>116869bb-0ade-4d22-b4df-350829645192</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='pros']</value>
      <webElementGuid>d95fe07e-6667-4032-b840-803d436068a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='foots']/button[2]</value>
      <webElementGuid>e6d50f17-51b2-45a5-b70c-22cad2bf962a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Batal'])[1]/following::button[1]</value>
      <webElementGuid>d3f13289-8d21-49c0-a47a-4aa3ce4d6621</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Paraf:'])[1]/following::button[2]</value>
      <webElementGuid>d3b01f9e-5513-48cd-a578-4b789cbf8be1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih Email Paraf :'])[1]/preceding::button[1]</value>
      <webElementGuid>947a5a5b-8bf3-40e0-8251-93a6399a800f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Set Email'])[1]/preceding::button[1]</value>
      <webElementGuid>e31e8977-0330-4cfd-9dd3-1a0fce95bf72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Proses']/parent::*</value>
      <webElementGuid>bf7d3a93-77a3-493a-ad49-6a91a7d4165f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[15]/div/div/div[2]/button[2]</value>
      <webElementGuid>f08dfd1c-c81e-4826-9843-9338854aff2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'pros' and (text() = ' Proses  ' or . = ' Proses  ')]</value>
      <webElementGuid>d1be1071-501f-4efb-bc40-57c643ee06f4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
