<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Tambah Saya</name>
   <tag></tag>
   <elementGuidId>cc0f17ed-16a0-442e-9ccb-cc4bb30bf93e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#add_me</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='add_me']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a6043aa8-cedb-445a-8c63-01f61f81bb69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btns btn-secondary mb-1</value>
      <webElementGuid>819ddd1a-e062-4cef-9347-b2b98ebf3e64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>add_me</value>
      <webElementGuid>ae62515d-1177-465c-ad99-d874683bd229</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Tambah Saya </value>
      <webElementGuid>15581fff-8b43-4be2-997a-6e5e3a5d52f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;add_me&quot;)</value>
      <webElementGuid>6e0ea652-6610-43d9-a757-b613ba3e5ffd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='add_me']</value>
      <webElementGuid>c7600206-3251-4416-8290-58367e5153d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama'])[1]/following::button[1]</value>
      <webElementGuid>18cace69-4ef1-4ee9-9ec0-fbe1f63ae16a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Penerima'])[1]/following::button[1]</value>
      <webElementGuid>c4bb832b-fd4d-4421-99fe-c34985ad2c0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[1]/preceding::button[1]</value>
      <webElementGuid>d2ce25eb-4b54-482f-b436-a83dcdd166f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dibutuhkan Tandatangan'])[2]/preceding::button[1]</value>
      <webElementGuid>0f545157-cebc-48ef-8d49-492bf68e4903</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tambah Saya']/parent::*</value>
      <webElementGuid>c8d6d404-bd8d-4447-8d49-c1fbdfc8190b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/button</value>
      <webElementGuid>a70036aa-53d7-4c6f-a4a4-cedeea8ab767</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'add_me' and (text() = ' Tambah Saya ' or . = ' Tambah Saya ')]</value>
      <webElementGuid>3dbc7d5b-76b2-44c0-9179-4cf896aad326</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
