<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Paraf</name>
   <tag></tag>
   <elementGuidId>c4e9fdff-7f8a-47fd-b111-d007ab85c59f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@onclick='adds_init()']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-light.mt-2.mb-2.text-dark</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>323f8663-d302-4a92-87e8-a111e12cc69c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-light mt-2 mb-2 text-dark</value>
      <webElementGuid>a517c1b2-bba1-4efd-a21b-3b96a14f94c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>adds_init()</value>
      <webElementGuid>01f2bbdb-28cb-44af-8b4c-5018a159d7d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
				   Paraf 				</value>
      <webElementGuid>642e51b9-81ae-4e2c-869a-a53a4250bd95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hdr&quot;)/div[@class=&quot;col text-center&quot;]/div[@class=&quot;btn-group grp&quot;]/button[@class=&quot;btn btn-light mt-2 mb-2 text-dark&quot;]</value>
      <webElementGuid>9e6b92cc-5bcf-4a3b-a193-9098dd92d850</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@onclick='adds_init()']</value>
      <webElementGuid>7467442c-1f63-46a3-8cc1-7fe3ceaba62e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hdr']/div/div[2]/button</value>
      <webElementGuid>ba581dd4-88ae-4aa1-8c8b-83b7e3b351a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please Wait'])[2]/following::button[4]</value>
      <webElementGuid>a5a7f0da-e7d3-4314-95d4-1a5ffb512573</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading page ...'])[1]/preceding::button[2]</value>
      <webElementGuid>1f654c3f-5ad4-4e78-b1dd-4e9abe41974b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Paraf']/parent::*</value>
      <webElementGuid>d96100df-f872-4ae5-9b8a-b97c1093cacc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>b3e7fe54-7591-4390-a1f7-9ed5bdf93ebb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = '
				   Paraf 				' or . = '
				   Paraf 				')]</value>
      <webElementGuid>323d61cc-c0de-48f9-9b83-9cd6d758ca1d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
