<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Format Email salah</name>
   <tag></tag>
   <elementGuidId>9e919372-85d1-4c31-ac94-83f37e44fa44</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#e_email-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='e_email-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3309def5-8d68-443d-ad04-d2a5adc8fad0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>e_email-1</value>
      <webElementGuid>072149c0-912b-484c-9a26-ec0aefd79a74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>notif</value>
      <webElementGuid>17e92f40-112e-4c1b-b691-56dfb5851f56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Format Email salah !</value>
      <webElementGuid>f716a9c1-ac9c-4ba2-ae94-abdb4f143c74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;e_email-1&quot;)</value>
      <webElementGuid>f85734ce-942c-4d2e-a934-a41f7ef0a2f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='e_email-1']</value>
      <webElementGuid>1513b602-a4c4-489b-8652-8594a3bad874</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[1]/following::div[1]</value>
      <webElementGuid>40b4e511-06b1-41d9-8aea-ee67db3eb0d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tambah Saya'])[1]/following::div[2]</value>
      <webElementGuid>c07c6d45-b4cf-4736-a6b9-3ee88c89a0b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dibutuhkan Tandatangan'])[2]/preceding::div[1]</value>
      <webElementGuid>9a1cff7b-a4ad-4397-96b7-51ac1388764d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tambah Penerima'])[1]/preceding::div[3]</value>
      <webElementGuid>9d535b50-e8e3-495c-ae4c-8b3edd560b04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Format Email salah !']/parent::*</value>
      <webElementGuid>471ee0ab-b4e2-4890-9474-bd8c171d9817</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[3]/div</value>
      <webElementGuid>abddd216-2819-45f7-b555-3aef1e45ed9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'e_email-1' and (text() = 'Format Email salah !' or . = 'Format Email salah !')]</value>
      <webElementGuid>f169ec4d-4b50-48b9-a6c4-ae71d284e931</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
