<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Paraf</name>
   <tag></tag>
   <elementGuidId>e0a0e8c4-3805-46d5-baa2-90ac61082e9e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='imginit-1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#imginit-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>974d4bf2-71ca-4c59-95a0-8c40834ed890</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>imginit-1</value>
      <webElementGuid>d163b8a1-c937-4957-9f96-b69e44416995</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fooinit green</value>
      <webElementGuid>d994a5ab-ea83-427a-a19a-91afe4651597</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Paraf</value>
      <webElementGuid>195287e4-4ddd-43c8-826b-7f6828931049</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;imginit-1&quot;)</value>
      <webElementGuid>4d429fb4-0cd0-4ed9-8ae7-f5a7a4e6e46e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='imginit-1']</value>
      <webElementGuid>3ddfeec5-559e-4814-9d66-b8068e81b6fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='widgetlockinit1']/div</value>
      <webElementGuid>b922ac8b-f62f-458d-9ff1-33d66325464c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading page ...'])[1]/preceding::div[3]</value>
      <webElementGuid>871e78de-469d-4fb3-89b2-dcb8646361b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/div/div[2]/div/div/div</value>
      <webElementGuid>d95cf3d8-f27b-4792-9d43-4b45078a62ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'imginit-1' and (text() = 'Paraf' or . = 'Paraf')]</value>
      <webElementGuid>7dfd07bc-3463-45b9-9aff-3ad9c67854c2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
