<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Simbol tidak dapat didukung sebagai isian</name>
   <tag></tag>
   <elementGuidId>ad122aca-0b7c-42ca-87b2-fb6f4b5c3d97</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='e_name-1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#e_name-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>46a9bc49-caaf-43a4-951c-7da8ec603130</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>e_name-1</value>
      <webElementGuid>b334eb7a-73c9-426d-8261-1313ebb10da0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>notif col-sm-12</value>
      <webElementGuid>8f03d7f9-2da6-4a33-af82-88dd7053c03a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Simbol tidak dapat didukung sebagai isian</value>
      <webElementGuid>dbe40347-7af8-4b2b-9d4f-a6f162dff26f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;e_name-1&quot;)</value>
      <webElementGuid>4da874bb-e03b-4a79-bb14-c017edecb6d3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='e_name-1']</value>
      <webElementGuid>6aad755a-3310-4377-b6c8-89d6b7addb92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama'])[1]/following::div[2]</value>
      <webElementGuid>5abe81f0-b4d4-4873-8240-5c1b242e2e8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Penerima'])[1]/following::div[5]</value>
      <webElementGuid>2e111103-f1c7-4d21-ba24-480e852d16fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tambah Saya'])[1]/preceding::div[1]</value>
      <webElementGuid>70c1f9be-e205-467f-b7ba-ec9b9ffc51e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[1]/preceding::div[1]</value>
      <webElementGuid>bf44035f-b557-445b-bbc2-808dee94dd55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Simbol tidak dapat didukung sebagai isian']/parent::*</value>
      <webElementGuid>2352710e-8551-4d8e-98ac-085409c24666</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/div/div</value>
      <webElementGuid>204793bd-9700-4ea5-8134-f69515b00320</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'e_name-1' and (text() = 'Simbol tidak dapat didukung sebagai isian' or . = 'Simbol tidak dapat didukung sebagai isian')]</value>
      <webElementGuid>4b5e6149-5538-442c-91f2-71acf071c5c0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
