<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Email penerima masih kosong</name>
   <tag></tag>
   <elementGuidId>70531c9d-0766-4554-ac5f-d3bf73fbf201</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#e_email-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='e_email-2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>52b6b259-1362-4ae3-8319-44bfd4000850</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>e_email-2</value>
      <webElementGuid>1387b391-57bd-4f97-b511-b75c775da949</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>notif</value>
      <webElementGuid>a7470759-d7ad-430d-88dd-8e3852c82ec9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Email penerima masih kosong !</value>
      <webElementGuid>13289990-e21f-4c30-948d-e37a8dbc0161</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;e_email-2&quot;)</value>
      <webElementGuid>1d1c0e84-b88c-4b94-89c1-319a550cda54</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='e_email-2']</value>
      <webElementGuid>5a8b318e-1b56-4e91-abdf-8224f1e8c2bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[2]/following::div[1]</value>
      <webElementGuid>17641431-c87e-4880-aed3-4d4c78da93ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama'])[2]/following::div[3]</value>
      <webElementGuid>eeb8a679-fcd0-4952-9dae-5302603bc695</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dibutuhkan Tandatangan'])[4]/preceding::div[1]</value>
      <webElementGuid>b1a4c2ba-8721-4099-8cfc-63c659919328</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tambah Penerima'])[1]/preceding::div[2]</value>
      <webElementGuid>6976618b-f6e1-443e-ac63-0169fe5c79b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Email penerima masih kosong !']/parent::*</value>
      <webElementGuid>1709881b-e107-4512-a7ab-dc9291bfc5aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[3]/div</value>
      <webElementGuid>0d6ecd6d-6a66-445e-9c06-583911a71f44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'e_email-2' and (text() = 'Email penerima masih kosong !' or . = 'Email penerima masih kosong !')]</value>
      <webElementGuid>88e2362c-66d6-47db-a1c6-afafa576743b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
