<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Nama penerima masih kosong</name>
   <tag></tag>
   <elementGuidId>e2311d11-eb7e-45ab-a28e-d504a184ff15</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#e_name-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='e_name-2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8ec493dc-93ec-4618-a114-18984f4c74fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>e_name-2</value>
      <webElementGuid>b5e3b09f-c73a-450c-820e-60e59bc533a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>notif</value>
      <webElementGuid>9af3c0c3-1b36-4054-b1e5-7b86559c82dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Nama penerima masih kosong !</value>
      <webElementGuid>5c5264d5-e524-440d-abcf-d1b906abbb51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;e_name-2&quot;)</value>
      <webElementGuid>3532f102-4429-4f3e-9638-91a6eddd7c51</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='e_name-2']</value>
      <webElementGuid>5a19ff4e-186e-4e93-9640-c64d4f592ed3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama'])[2]/following::div[1]</value>
      <webElementGuid>4178beb1-91b0-4a07-96e8-06e54172007c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dibutuhkan Tandatangan'])[2]/following::div[6]</value>
      <webElementGuid>699a0d53-2b4a-468c-8236-be950081629a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[2]/preceding::div[1]</value>
      <webElementGuid>282c1694-4840-41ce-a0d9-661b8ff14b55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dibutuhkan Tandatangan'])[4]/preceding::div[3]</value>
      <webElementGuid>4a79a402-b74c-4662-9305-a2850912fdb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Nama penerima masih kosong !']/parent::*</value>
      <webElementGuid>6ffb2d13-c4e1-4eca-b145-c5307c7c1a8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/div</value>
      <webElementGuid>76494d1a-1a17-4874-9ec1-0a73ae86381b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'e_name-2' and (text() = 'Nama penerima masih kosong !' or . = 'Nama penerima masih kosong !')]</value>
      <webElementGuid>4e887916-2200-44ad-8106-27ccdd22dc9e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
