<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Format Email salah</name>
   <tag></tag>
   <elementGuidId>9e919372-85d1-4c31-ac94-83f37e44fa44</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='e_email-1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#e_email-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4ab4d7d6-957b-450d-b148-1f7d6aae4804</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>e_email-1</value>
      <webElementGuid>194e33ac-6d4a-41e7-b012-7071bf65f118</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>notif</value>
      <webElementGuid>fa0356c5-895e-4343-8edc-b823f86734df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Format Email salah !</value>
      <webElementGuid>49aebce4-1ac9-4582-bea3-a201003f53df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;e_email-1&quot;)</value>
      <webElementGuid>2e71b11e-5ed9-48a3-990f-4927920de2a4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='e_email-1']</value>
      <webElementGuid>b67be690-1854-473c-a4fa-e2f9d7122fdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[1]/following::div[1]</value>
      <webElementGuid>1c2d830e-a817-450d-97cd-bda3ffa2f6b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tambah Saya'])[1]/following::div[2]</value>
      <webElementGuid>458de3b8-7eac-420b-9ea4-94e9b21e7eaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dibutuhkan Tandatangan'])[2]/preceding::div[1]</value>
      <webElementGuid>5d6abd5b-d6c7-4605-a0bc-532f76fb203f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tambah Penerima'])[1]/preceding::div[3]</value>
      <webElementGuid>ddb708c2-9367-4205-85cf-f9bd73d76c93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Format Email salah !']/parent::*</value>
      <webElementGuid>0ebae6c9-ef1c-4e73-b014-97c50ab39e71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[3]/div</value>
      <webElementGuid>61d3fa6c-ddae-4b9c-be4e-169bf9a5c8a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'e_email-1' and (text() = 'Format Email salah !' or . = 'Format Email salah !')]</value>
      <webElementGuid>31d01e73-d4b8-403f-a909-57abc1864421</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
