<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Dokumen berhasil dikirim</name>
   <tag></tag>
   <elementGuidId>83698c89-5dc4-41fb-89fe-5466f08de38d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='swal2-content']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#swal2-content</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>afc62e2e-b0ad-462f-a330-2b93f9b780c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>swal2-content</value>
      <webElementGuid>2f8eb920-6a88-4ff3-8a94-2cd8f1c97186</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dokumen berhasil dikirim</value>
      <webElementGuid>2d017076-26dd-49ce-bd49-be5224776c92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;swal2-content&quot;)</value>
      <webElementGuid>6b2cfbf8-cc2e-4fad-aae4-0cf4c08ee438</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='swal2-content']</value>
      <webElementGuid>f96ce5c3-c62f-4d2c-a533-ad2e197f859c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ã—'])[1]/following::div[2]</value>
      <webElementGuid>d78c24bd-7d12-4565-a73c-131cef1b8768</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='i'])[1]/following::div[7]</value>
      <webElementGuid>fa6f3bbe-a22d-48d6-8ae0-4577c1d9b5bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OK'])[1]/preceding::div[4]</value>
      <webElementGuid>6b832e07-0f5c-4383-877d-33a506f8cf5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::div[4]</value>
      <webElementGuid>e89597d8-7939-400c-bc74-58d7094312de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Dokumen berhasil dikirim']/parent::*</value>
      <webElementGuid>f791782f-6e41-40ab-a9ad-e85d2c8a12aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div</value>
      <webElementGuid>f52d5652-efe5-4d41-9c0f-13fcd72be579</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'swal2-content' and (text() = 'Dokumen berhasil dikirim' or . = 'Dokumen berhasil dikirim')]</value>
      <webElementGuid>e5d678ae-b35e-4792-a833-00aaa8bce1c0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
