<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Sign Here</name>
   <tag></tag>
   <elementGuidId>5da44e43-8c28-475f-8cf8-6190cccea323</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#img-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='img-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d0b16cfb-c7af-44f6-babb-5823905bc27e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>img-1</value>
      <webElementGuid>5e4f58b4-e844-4f60-97a1-9cb2e780eded</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>foo blue ui-resizable</value>
      <webElementGuid>578fdeb7-aca7-400d-ba6c-f1921e74ea7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sign Here</value>
      <webElementGuid>1b3783b1-0555-4198-a7b8-6f8be308c835</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;img-1&quot;)</value>
      <webElementGuid>7768f9e5-db9e-45a5-bea1-3798ce7c5977</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='img-1']</value>
      <webElementGuid>112fb52c-4777-41f7-bd23-c2fd7befad8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='widgetlock1']/div</value>
      <webElementGuid>86346d4f-ab71-4071-8365-5377654f8fbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading page ...'])[1]/preceding::div[4]</value>
      <webElementGuid>ce3f57ae-86f4-4178-940a-96c075fd1c83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/div/div[2]/div/div/div</value>
      <webElementGuid>321d3cbd-932b-4552-94de-60861dfd7901</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'img-1' and (text() = 'Sign Here' or . = 'Sign Here')]</value>
      <webElementGuid>3bd36be5-6041-4c4c-9883-741f9a829add</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
