<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Paraf</name>
   <tag></tag>
   <elementGuidId>e0a0e8c4-3805-46d5-baa2-90ac61082e9e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#imginit-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='imginit-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>eb9e73f1-5e6f-4239-8eb5-b4a1d443051c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>imginit-1</value>
      <webElementGuid>35ef38db-8c49-4e28-9c00-b8865d63053c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fooinit green</value>
      <webElementGuid>be19fb26-ca55-4372-aaf3-0ddde8d5c818</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Paraf</value>
      <webElementGuid>0389b1e0-0e80-4d3b-8914-c4c203a51b7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;imginit-1&quot;)</value>
      <webElementGuid>d1e6fc38-de5c-4290-8223-e3dd6e31ca70</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='imginit-1']</value>
      <webElementGuid>e22d39d7-84cf-408e-b25c-496e05486e18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='widgetlockinit1']/div</value>
      <webElementGuid>d93a39fc-3e57-49e3-9592-349f57dbb00e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading page ...'])[1]/preceding::div[3]</value>
      <webElementGuid>9917ed88-aba1-4b43-b544-14d3c4fc8faf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/div/div[2]/div/div/div</value>
      <webElementGuid>32fc892f-ddf4-4c7c-a5b5-64f916be8ff0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'imginit-1' and (text() = 'Paraf' or . = 'Paraf')]</value>
      <webElementGuid>87f7872a-979e-4283-bdcd-4d65fb46be06</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
