<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nama_name-2</name>
   <tag></tag>
   <elementGuidId>e2d71fee-b46d-41c3-a7fc-839301f5c844</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#name-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='name-2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2bfb88b1-1b81-43b2-8522-3c548ae5f67a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d2e08375-207c-421c-8167-6bdbb24fe525</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>name-2</value>
      <webElementGuid>c57a6a53-d638-4cfd-a827-5f57bfe65d10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>c1d3aec2-0f44-4d2b-85b7-d7ea9f745a78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>nama</value>
      <webElementGuid>ac854bad-53e0-4c2d-96e0-47c918bae675</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;name-2&quot;)</value>
      <webElementGuid>175b6dba-4e33-41e5-b94c-ad6d23107de1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='name-2']</value>
      <webElementGuid>b4c07847-8052-44cb-bfce-4365ec1fecca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/input</value>
      <webElementGuid>51139900-4552-4f97-95e3-ffa95455d16e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'name-2' and @placeholder = 'nama']</value>
      <webElementGuid>2c1172e7-89a7-4a6b-a7b7-62c4dd0c626d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
