<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_email-2</name>
   <tag></tag>
   <elementGuidId>45226dcd-22b6-4389-ba90-6b6300b5db58</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#email-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='email-2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>914b6278-739d-438e-8c02-daebaeb7ce1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>299d69e5-ef31-4bd2-9f39-3f878e42f1d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>0641903c-0fee-4b15-8aa9-98e7d25b697a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>email-2</value>
      <webElementGuid>c890e72d-b40e-4a7a-8cf3-a2074efe31c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>3e11c68f-7db5-4842-aa0f-75f9a792cbce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;email-2&quot;)</value>
      <webElementGuid>8cd15100-bb51-48c8-941f-8d2ee245a5ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='email-2']</value>
      <webElementGuid>2b289438-5bed-4131-9937-f343da25ee58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[3]/input</value>
      <webElementGuid>73916ed0-06b9-44e9-8ab9-3c9c6aae58d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @id = 'email-2' and @placeholder = 'email']</value>
      <webElementGuid>366341a6-7300-46f4-92b5-b21463d141aa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
