<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_email-1</name>
   <tag></tag>
   <elementGuidId>d37830f9-48fe-476c-84f3-0d4ceff20857</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#email-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='email-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9c5920ec-8d41-4b58-bea7-9c3225383162</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>de4f7a5c-9398-4f2e-afaf-af6bf18b9612</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>d3e34159-baf8-44c4-85f0-d3eeb6e2678a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>email-1</value>
      <webElementGuid>ebeca1ce-c9b8-473f-be2f-6bfec0315a00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>valalnum('e_email-1')</value>
      <webElementGuid>264d7a2c-c24a-47c1-a9f5-9bef0ad7097c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>bfcdc126-ecff-4577-8dbe-89fdbbc75e3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;email-1&quot;)</value>
      <webElementGuid>7121a430-a54d-4359-83bf-0bd90f390946</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='email-1']</value>
      <webElementGuid>0d90efe3-4782-4ac2-8d20-93b5eb029602</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/input</value>
      <webElementGuid>6a0f7798-a4b1-430b-a4c4-db987f79e609</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @id = 'email-1' and @placeholder = 'email']</value>
      <webElementGuid>a5631381-4536-4bd1-95ec-45662aec3806</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
