<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>selectaction</name>
   <tag></tag>
   <elementGuidId>71f53539-8602-4b4f-804e-4a09d9e53c19</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-ck1-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='ck1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a2ce7c21-c7d1-4c55-b52b-a167d1beeddd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>f6d275ab-cca7-4951-baa3-cf6371f9cb94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-ck1-container</value>
      <webElementGuid>a7d48c70-52cd-439d-a565-5851d6d10020</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value> Dibutuhkan Tandatangan  </value>
      <webElementGuid>4f8096f1-a4d9-4a2e-a44a-72e0226d4f73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Dibutuhkan Tandatangan  </value>
      <webElementGuid>692ca453-c913-4d47-8fac-4900d996ed61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-ck1-container&quot;)</value>
      <webElementGuid>19b032a6-b6bd-4092-971d-66d2f4be596a</webElementGuid>
   </webElementProperties>
</WebElementEntity>
