<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>selectaction</name>
   <tag></tag>
   <elementGuidId>71f53539-8602-4b4f-804e-4a09d9e53c19</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='ck1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-ck1-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ef9773c9-025b-4cd9-b297-0af7a42668cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>8111d0d1-e803-45fb-a80d-ed2f666984da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-ck1-container</value>
      <webElementGuid>656b097f-12ff-45ce-8591-7bdb31a86337</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value> Dibutuhkan Tandatangan  </value>
      <webElementGuid>45e9c025-4fe2-423e-974f-83bf121afe0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Dibutuhkan Tandatangan  </value>
      <webElementGuid>742628c9-875d-43c8-b53c-8cc52597b609</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-ck1-container&quot;)</value>
      <webElementGuid>038f2ed3-8d70-4a38-acdc-797eaf2ce42a</webElementGuid>
   </webElementProperties>
</WebElementEntity>
