<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Sign Here_fa  fa-unlock-alt fa-2x</name>
   <tag></tag>
   <elementGuidId>bff1d451-9124-41c6-b2a4-ff97798169b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.fa.fa-unlock-alt.fa-2x</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='lock1']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ef22cb98-45d6-4a72-b0e3-535e0458da7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa  fa-unlock-alt fa-2x</value>
      <webElementGuid>f619581b-4bfc-4c07-a3b6-920b4787af61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>88e03bab-9903-4a65-b764-36209168befa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lock1&quot;)/span[@class=&quot;fa  fa-unlock-alt fa-2x&quot;]</value>
      <webElementGuid>2604aeba-0bc7-476a-9efa-db60ee94bc75</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='lock1']/span</value>
      <webElementGuid>d860028a-8518-44aa-8cb2-d271bcec37ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/button/span</value>
      <webElementGuid>ca968c3e-7e95-45fe-8c05-0ffebfd1abf7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
