<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Dibutuhkan Tandatangan</name>
   <tag></tag>
   <elementGuidId>f9d2ccc4-00a5-4c7a-a050-56c6353883d5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-ck1-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-ck1-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f85da641-17e7-423d-906b-52c023d88e89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>bd0db1d6-dd50-484a-947f-4ae7a50ff90a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-ck1-container</value>
      <webElementGuid>c256c663-0436-4b1a-80d6-7e4e11db1b5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value> Dibutuhkan Tandatangan  </value>
      <webElementGuid>c9f13af9-0db4-4f3b-82ef-679673ea2dc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Dibutuhkan Tandatangan  </value>
      <webElementGuid>a82ae4f6-daaf-4cfc-9646-fd2330bf11a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-ck1-container&quot;)</value>
      <webElementGuid>42e61761-d0ec-429d-aad5-3d5a2d33e35f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-ck1-container']</value>
      <webElementGuid>e7aa8777-0df0-4f53-ba99-5685385a2fed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[1]/following::span[4]</value>
      <webElementGuid>fb191ecb-a193-4595-842d-72941952da24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tambah Saya'])[1]/following::span[4]</value>
      <webElementGuid>c248b90d-bb5f-49f9-ba78-e93422af4c92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tambah Penerima'])[1]/preceding::span[3]</value>
      <webElementGuid>7622b196-fc33-413f-909d-98db77868571</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kembali'])[1]/preceding::span[3]</value>
      <webElementGuid>b44767ae-8363-401e-ba79-8c11b172b972</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/span</value>
      <webElementGuid>d7fa4d58-4720-4269-aa30-008ff898e992</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-ck1-container' and @title = ' Dibutuhkan Tandatangan  ' and (text() = ' Dibutuhkan Tandatangan  ' or . = ' Dibutuhkan Tandatangan  ')]</value>
      <webElementGuid>840e3ab5-8b61-4bd4-a9fb-e19e93dadd12</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
