<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Paraf_fa fa-plus-circle fa-lg</name>
   <tag></tag>
   <elementGuidId>01ea702f-d07f-4a94-9842-0844f46b94c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.fa.fa-plus-circle.fa-lg</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='hdr']/div/div[2]/button/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>91347554-f6c2-4e49-a9fd-aef5c191d878</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>fdce87ac-6a25-481f-aad2-dcd85073cb19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-plus-circle fa-lg</value>
      <webElementGuid>38470053-f77a-43c0-b08d-ff07f5f6bf71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hdr&quot;)/div[@class=&quot;col text-center&quot;]/div[@class=&quot;btn-group grp&quot;]/button[@class=&quot;btn btn-light mt-2 mb-2 text-dark&quot;]/span[@class=&quot;fa fa-plus-circle fa-lg&quot;]</value>
      <webElementGuid>fcbb4b89-e1ec-4555-942a-c7a4718cbdcb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hdr']/div/div[2]/button/span</value>
      <webElementGuid>efd07c74-cc72-4311-a628-87bdb752a1e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button/span</value>
      <webElementGuid>5f5d985d-ec74-41f6-b68a-9618a288b68b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
