<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Sign Here_fa  fa-unlock-alt fa-2x</name>
   <tag></tag>
   <elementGuidId>bff1d451-9124-41c6-b2a4-ff97798169b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='lock1']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.fa.fa-unlock-alt.fa-2x</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6dcd0c9f-8bc3-4937-b0b2-8af4cd8f521a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa  fa-unlock-alt fa-2x</value>
      <webElementGuid>52c38049-4308-407c-bc80-4d881c0f6ab9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b5d49990-4f21-4609-8be9-326704d7c294</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lock1&quot;)/span[@class=&quot;fa  fa-unlock-alt fa-2x&quot;]</value>
      <webElementGuid>763b337a-7ea9-4947-9144-87e0dccb0efd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='lock1']/span</value>
      <webElementGuid>97d3789c-208e-4f03-8ce0-6a8903f07e15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/button/span</value>
      <webElementGuid>436540c9-a7bb-4e0e-bd61-b236cbf1325d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
