<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Sign Here_fa fa-lock fa-2x</name>
   <tag></tag>
   <elementGuidId>1ce70d6a-d040-4a0a-8728-8036341b2f74</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='lock1']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.fa.fa-lock.fa-2x</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d98d67e0-2712-48a1-854b-934da816f504</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-lock fa-2x</value>
      <webElementGuid>001369ef-0786-4df3-a40d-551fd41bbfba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>cbc9db4c-7582-4f1c-80bd-05eb61f04214</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lock1&quot;)/span[@class=&quot;fa fa-lock fa-2x&quot;]</value>
      <webElementGuid>bad0493a-69d5-48b7-ac1f-5a51ff6c2a18</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='lock1']/span</value>
      <webElementGuid>e626b37d-101c-4ef4-92d6-b379eaf222ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/button/span</value>
      <webElementGuid>e8b15131-63c3-4387-b299-5cd44703d879</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
