<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Tandatangan</name>
   <tag></tag>
   <elementGuidId>0b2df8a4-d3d2-455d-aa08-33d464da8fc1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Kotak Masuk Terakhir'])[1]/following::a[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.text-white</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ae36e026-f127-47fe-94d0-83de3eaa89b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tooltip</value>
      <webElementGuid>8746d87e-49b6-4932-9e8a-e4f3beff66cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Tandatangani Dokumen</value>
      <webElementGuid>b9cc43cc-7f23-4a88-9e59-ea9139941c65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>../doc/pdf.html?enc=5rPRgtL4mHS59wlmMCTzGjsQHPJQ0Zv+wx%2FetLYBG5Q%3D</value>
      <webElementGuid>63328577-5c53-4da0-af0c-847326185d05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-white</value>
      <webElementGuid>e496724f-1d2e-4b7e-9ff0-59343576ec99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                Tandatangan  </value>
      <webElementGuid>04459ec9-41e8-4ca0-89f6-3a27d06dd60f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;js flexbox canvas canvastext webgl no-touch geolocation postmessage websqldatabase indexeddb hashchange history draganddrop websockets rgba hsla multiplebgs backgroundsize borderimage borderradius boxshadow textshadow opacity cssanimations csscolumns cssgradients cssreflections csstransforms csstransforms3d csstransitions fontface generatedcontent video audio localstorage sessionstorage webworkers no-applicationcache svg inlinesvg smil svgclippaths&quot;]/body[1]/div[@class=&quot;page-container&quot;]/div[@class=&quot;main-content&quot;]/div[@class=&quot;main-content-inner&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12&quot;]/div[@class=&quot;card&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;data-tables&quot;]/div[@class=&quot;dataTables_wrapper dt-bootstrap4 no-footer&quot;]/div[@class=&quot;table-responsive&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row pointer text-dark border-bottom  p-1&quot;]/div[@class=&quot;col-sm-6 col-md-4 col-lg-3 mt-2&quot;]/div[@class=&quot;d-flex justify-content-between&quot;]/span[@class=&quot;status-p bg-danger&quot;]/a[@class=&quot;text-white&quot;]</value>
      <webElementGuid>100636c2-6a5a-4f69-8afe-5bd01b6bbc8f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kotak Masuk Terakhir'])[1]/following::a[2]</value>
      <webElementGuid>265329ba-a5dd-4bcb-b763-f84dab33a766</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Id. MT300000397379'])[1]/preceding::a[1]</value>
      <webElementGuid>a4b5f0f4-5d40-43be-9117-8e9c1f83885f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tandatangan']/parent::*</value>
      <webElementGuid>5cdf5b36-dc13-440b-a1ee-816a97d97c6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '../doc/pdf.html?enc=5rPRgtL4mHS59wlmMCTzGjsQHPJQ0Zv+wx%2FetLYBG5Q%3D')]</value>
      <webElementGuid>84769837-7dcc-4bc4-aedc-f60a7c1cdda5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/a</value>
      <webElementGuid>b54251f0-71dc-4cdd-9171-ce67c31d4fae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'Tandatangani Dokumen' and @href = '../doc/pdf.html?enc=5rPRgtL4mHS59wlmMCTzGjsQHPJQ0Zv+wx%2FetLYBG5Q%3D' and (text() = '
                                Tandatangan  ' or . = '
                                Tandatangan  ')]</value>
      <webElementGuid>b9066832-2e4f-4037-8bd7-cd1099f9a41d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
