<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Wahyu Hidayat_100658</name>
   <tag></tag>
   <elementGuidId>b36cf78d-539b-44c0-a4fc-9849b0226061</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pd</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='pd']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bb29a9ce-e7fc-4a1f-a1bd-4768cafaf5e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pd</value>
      <webElementGuid>10555d14-e01b-4ec7-9414-d72630dd7d0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>2769f4b0-69b3-4fd5-b5f4-6b46ba792520</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>e3cd9f9d-090b-46eb-88f5-fd0e8cadc3a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>100658</value>
      <webElementGuid>fed850df-b38f-4316-b775-54e4bae55111</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>257d4721-8657-408e-8278-16cddffabdb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pd&quot;)</value>
      <webElementGuid>b842a78c-c7d5-456f-bf18-df5c5a884b38</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='pd']</value>
      <webElementGuid>71105ee5-6c61-4df3-ace1-feaa995b3105</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pdform']/input</value>
      <webElementGuid>7fa00b7f-629d-4e7d-95bb-b9d680095756</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>052ceabf-94c0-4ed1-85d9-3265b9e33183</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'pd' and @type = 'password' and @name = '100658' and @placeholder = 'password']</value>
      <webElementGuid>b3fabcc3-3ed5-4f7f-b596-48e0fa369d93</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
