<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Wahyu Hidayat_168098</name>
   <tag></tag>
   <elementGuidId>10f2a6e0-83e4-4059-84b1-790219672749</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pd</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='pd']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>44403e16-002e-40f9-a8b5-889b817603d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pd</value>
      <webElementGuid>163eeace-4828-4cf1-849f-e6dba734778a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>b01e7562-097d-44e3-aa76-8d7d4e158185</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>f0506743-d574-444c-aa53-15cd9e6a26f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>168098</value>
      <webElementGuid>761f2b19-50e7-4506-903a-4eb0880c9f4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>e2910253-0b4e-4fb2-9c99-77de52895c06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pd&quot;)</value>
      <webElementGuid>26063fb1-c55f-41e6-934d-b08d49e60445</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='pd']</value>
      <webElementGuid>afce18b9-22ca-476f-8f19-3b1be225dd12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pdform']/input</value>
      <webElementGuid>74e68789-f2da-46f6-bb9b-4ce5c7ea3162</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>697fc0d3-a22e-4e1e-9858-1716bff91bc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'pd' and @type = 'password' and @name = '168098' and @placeholder = 'password']</value>
      <webElementGuid>2f6c2f20-6892-47d0-805e-307da21a63f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
