<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Kata sandi baru_pd</name>
   <tag></tag>
   <elementGuidId>3b9d0815-0ecf-45cc-92cd-3399e9d87eaf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='pd']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#pd</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4cdffe9f-005a-4f1e-b7ca-220f8da54185</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-md</value>
      <webElementGuid>86e1a8f7-ccf2-4b9f-8bcf-b04af5c49fbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>validatePwd()</value>
      <webElementGuid>76dc6e90-016b-48a8-9aab-f8f7a2d24cde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pd</value>
      <webElementGuid>f22ea06e-4229-4128-aae9-3156a01690b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>6352e394-164e-4cf2-bb55-6d4f5add50b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value> Kombinasi huruf dan angka  </value>
      <webElementGuid>91c3b759-f053-4d63-a8f8-7fc6e5a4210c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>c759daa3-9f28-4541-82ce-0d51a8341737</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pd&quot;)</value>
      <webElementGuid>7e4a9a2c-df3d-4358-a56d-9ca89dd3ed2a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='pd']</value>
      <webElementGuid>ed1be92c-083b-4305-8397-5244111b9479</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='update']/div[2]/div/input</value>
      <webElementGuid>6b21e32c-4a6b-4662-97ec-54c0d28e6506</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>61f5cee5-7bca-4cc4-97aa-5167ecf57c3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'pd' and @type = 'password' and @placeholder = ' Kombinasi huruf dan angka  ']</value>
      <webElementGuid>4222d690-ee67-4c0a-b009-7a5ca5738670</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
