<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Silakan masukkan Email Baru Anda. Kam_25fccc</name>
   <tag></tag>
   <elementGuidId>0439db25-fa94-4460-8a25-92d200f2ab7e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#codeId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='codeId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ee256199-47f5-4c35-ad0d-e0db15b968bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>6 Digits</value>
      <webElementGuid>03cd366c-efb8-4949-9dc6-9a1d54c888e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>9c6b505a-9bad-4b15-8763-f3b6eebd98eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>codeId</value>
      <webElementGuid>e5e333be-301d-46a7-924b-203f33ffe2eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>codeId</value>
      <webElementGuid>9ccbc0a0-0501-4c9b-a6d8-3cce7ab44655</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>NumOnly form-control input-md</value>
      <webElementGuid>43d260cd-8a26-40d1-bca2-521d9dee1ecc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>81eb3cc8-a953-4041-bfcc-2d09a3a08442</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;codeId&quot;)</value>
      <webElementGuid>e5732d19-3b6e-420a-bfdb-0459ab5838ea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='codeId']</value>
      <webElementGuid>de8e96af-59a1-4413-b0cf-e5d157179363</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='changeEmail']/div[3]/div/div/div/input[2]</value>
      <webElementGuid>48110b6c-6f27-469f-bdd5-1d89ce57e595</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>8be37e59-250e-4407-8c30-2e7aca06d303</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = '6 Digits' and @type = 'tel' and @name = 'codeId' and @id = 'codeId']</value>
      <webElementGuid>17c47046-1cd8-4edd-b769-43bc1dc3f66c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
