<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Silakan masukkan Email Baru Anda. Kam_e93593</name>
   <tag></tag>
   <elementGuidId>a610af0e-8b70-4ffe-81ee-bb8f86af4606</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nick</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nick']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7bcb0cd7-f3d1-4fd2-9116-9f7d7e48cb02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ea5f795a-8899-4e4d-b51a-c65f9d82a47b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan alamat email baru Anda</value>
      <webElementGuid>d31fb387-0066-4e20-b6cb-4e9d223b516f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>validateEmail('e_nick')</value>
      <webElementGuid>774443a1-4fc5-4c5c-a802-d1d525d3b7b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nick</value>
      <webElementGuid>d6d36fd2-e0a3-45d8-8d2b-e6ab95424dca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-md</value>
      <webElementGuid>96bdab04-6f94-4b31-9640-a4a5a48112a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nick</value>
      <webElementGuid>68362337-e7a6-43ae-b26b-f35b7645dc56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>bf464698-7563-4232-b682-601b08a44e32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nick&quot;)</value>
      <webElementGuid>2477d762-e821-4790-9fbb-697b2c6690c0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nick']</value>
      <webElementGuid>5a3bfc0e-cd98-4844-802a-1a38444d678b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='changeEmail']/div[2]/div/input</value>
      <webElementGuid>f771f6b5-198e-4930-92ec-1789031f8a1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>df333dc8-6658-43a8-a591-7125e94d050d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Masukkan alamat email baru Anda' and @id = 'nick' and @name = 'nick']</value>
      <webElementGuid>142516bd-9e00-42ca-ab9e-c908139b5f3a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
