<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Ubah Tanda Tangan</name>
   <tag></tag>
   <elementGuidId>820a91fd-e6a6-4692-9fb4-f45908b4b950</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Ubah</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='Ubah']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>739aca7f-95b2-420f-862b-63a8a009bc51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Ubah</value>
      <webElementGuid>b4910c38-56b3-44ed-ab6e-bb2d98ad8656</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>88b8231b-df8c-4507-9476-925e83f184bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>cttd()</value>
      <webElementGuid>2aa3b895-f2d5-4ff7-802c-f0b716035c4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-danger</value>
      <webElementGuid>b2f20785-f1fc-4a30-9b84-7d483bb3d8ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Ubah Tanda Tangan  </value>
      <webElementGuid>4a578687-0013-429b-b8d2-316b681a8760</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Ubah&quot;)</value>
      <webElementGuid>0ca74185-c9c7-43ac-9bfa-61cedc5d8d9e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='Ubah']</value>
      <webElementGuid>d6a559b8-938b-4668-a330-e4dda7f55604</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ttd']/label/button</value>
      <webElementGuid>53342668-0911-4957-998c-2d07689a1955</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please Wait'])[2]/following::button[1]</value>
      <webElementGuid>e3193d50-1067-460c-a1e3-1d38bdf127ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hapus Tanda Tangan'])[1]/preceding::button[1]</value>
      <webElementGuid>d6836f12-6e3e-4a59-a876-daf06b2f1380</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ubah Tanda Tangan']/parent::*</value>
      <webElementGuid>09246fdc-e84e-4612-95a1-bdfc98c9be2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/button</value>
      <webElementGuid>d64de061-65e9-48aa-984b-4fffa44a4e9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'Ubah' and @type = 'button' and (text() = ' Ubah Tanda Tangan  ' or . = ' Ubah Tanda Tangan  ')]</value>
      <webElementGuid>b5ad5b1d-8466-427a-b863-eb696e714fba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
