<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>canvas_Hapus Tanda Tangan_signature-pad</name>
   <tag></tag>
   <elementGuidId>14ec2a6a-dca3-4ab5-a22f-a9ab1ab9396e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#signature-pad</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//canvas[@id='signature-pad']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>canvas</value>
      <webElementGuid>88a3f353-f9d5-4d6f-9da5-1d35b730d58a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>signature-pad</value>
      <webElementGuid>fa026140-1fe3-4f3c-bf35-83447f3adf74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>signature-pad</value>
      <webElementGuid>2e4cbc03-020a-4465-8d65-993609cfa9ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>400</value>
      <webElementGuid>08277c29-76b8-46ef-9102-4e5497e0d893</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>d5f540ba-5772-4862-8858-a4a6cc312f04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;signature-pad&quot;)</value>
      <webElementGuid>7dd0ff7f-9e54-458c-bda6-31d84930dd92</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//canvas[@id='signature-pad']</value>
      <webElementGuid>6228454b-fa1b-46a0-9b69-33eb571957ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wls']/div/canvas</value>
      <webElementGuid>09a9ce38-4aaa-4dfa-80ae-4b2e571740a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//canvas</value>
      <webElementGuid>16a319af-e616-4775-b022-c0b9db6ce271</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//canvas[@id = 'signature-pad']</value>
      <webElementGuid>4c6f76a8-00f5-4bd0-a608-a8f1c0caae5f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
