<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_SMS</name>
   <tag></tag>
   <elementGuidId>2c02d5ff-800a-43ca-ba02-10a192560502</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnotp</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnotp']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b3d81716-2296-4902-a3b2-0de5cc04faa0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnotp</value>
      <webElementGuid>eb61d0f6-3ebb-43be-aee2-46c7609b633d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7fa8c575-f531-4357-8e5c-665ab109891f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-info</value>
      <webElementGuid>1a86e953-2a63-423a-a95c-dd772571d1f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>otp(path,'1')</value>
      <webElementGuid>08badb09-d8cc-48eb-a7c8-974235da20d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                              	 SMS
                              </value>
      <webElementGuid>5a133f97-9f1f-4402-b1c3-dcbe519dd321</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnotp&quot;)</value>
      <webElementGuid>09c49234-f26c-416b-b701-b03fb4075580</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnotp']</value>
      <webElementGuid>7b7e4b10-c7b5-4c46-9b5b-e25798ddbb8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='otpModal']/div/div/div[2]/div[2]/div[3]/div/div/button</value>
      <webElementGuid>b7b729e7-2f95-4d08-8ad4-341f8995a241</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tidak terima, Kirim kembali OTP ?'])[1]/following::button[1]</value>
      <webElementGuid>374bf386-c8de-47eb-ae5b-83b22ecf37ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Masukkan OTP'])[1]/following::button[1]</value>
      <webElementGuid>3e9043d7-421e-4df3-ae1f-a84ae5a013d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Proses Dokumen'])[1]/preceding::button[2]</value>
      <webElementGuid>f0a2da39-db38-42cc-ab22-e9dc3d9d1f8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='SMS']/parent::*</value>
      <webElementGuid>5f7681cf-04c1-494e-bfc4-1e5bb9bffb6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/button</value>
      <webElementGuid>192c6923-643a-4b44-b00e-f1d2cf998103</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btnotp' and @type = 'button' and (text() = '
                              	 SMS
                              ' or . = '
                              	 SMS
                              ')]</value>
      <webElementGuid>2f0cbc72-77dd-4970-803d-47e0f32d18f6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
