<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Proses Dokumen</name>
   <tag></tag>
   <elementGuidId>a7923daf-6974-4664-af42-a394d11ab582</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#prosign</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='prosign']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>44cb90b9-6dca-4dd3-be33-eacf0112f649</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success btn-block</value>
      <webElementGuid>35541f61-44a6-471b-a910-56dbbd0ea5c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f9d1336e-c16f-4188-8e48-9124f22b801c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>prosign</value>
      <webElementGuid>0e568096-4641-4072-8c56-bf5e3f41633d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>confirmCertificate()</value>
      <webElementGuid>ce623e79-5c68-4649-9d4e-10b4af14773c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                      Proses Dokumen  </value>
      <webElementGuid>feea98f7-e2f5-4865-9d4c-ea833d5d8f8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;prosign&quot;)</value>
      <webElementGuid>44f5041c-7fb0-4ec8-aa1d-896673a4bcd1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='prosign']</value>
      <webElementGuid>1a7f3eb7-78eb-4b59-9bfd-ff846a861d8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='otpModal']/div/div/div[2]/div[3]/button</value>
      <webElementGuid>3883a19d-a33c-4426-9d83-ca2f5cfe4f40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kebijakan Privasi'])[1]/preceding::button[1]</value>
      <webElementGuid>8d062fbb-61a3-4810-94a1-c70c099af0db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Proses Dokumen']/parent::*</value>
      <webElementGuid>85b901cf-3c5f-4178-9dfc-66396d23de36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/button</value>
      <webElementGuid>4b37864b-2f77-4149-ab00-47ad4463785e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'prosign' and (text() = '
                      Proses Dokumen  ' or . = '
                      Proses Dokumen  ')]</value>
      <webElementGuid>233f9046-17b2-4138-856e-253656b61773</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
