<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_SMS</name>
   <tag></tag>
   <elementGuidId>2c02d5ff-800a-43ca-ba02-10a192560502</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnotp']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btnotp</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>003a28c0-5aa9-45f0-955e-bed84190306b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnotp</value>
      <webElementGuid>5685b8ed-4bdd-49c6-8aa6-259737e8c5e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a3a4b26f-831a-45a8-9bef-4442d59d4ddb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-info</value>
      <webElementGuid>5a33214e-5054-44fd-adbe-21311b8a473d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>otp(path,'1')</value>
      <webElementGuid>dbbddc32-51bb-460d-990a-da471aff2bc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                              	 SMS
                              </value>
      <webElementGuid>4967a1de-7554-4db7-9c34-5a5bf9466ad7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnotp&quot;)</value>
      <webElementGuid>22fd7105-a242-4db0-bdde-8df04298b801</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnotp']</value>
      <webElementGuid>f94edb10-c30f-43cb-9417-8c00e923a494</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='otpModal']/div/div/div[2]/div[2]/div[3]/div/div/button</value>
      <webElementGuid>30647488-25b0-4ca9-b67d-76dc75bcb416</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tidak terima, Kirim kembali OTP ?'])[1]/following::button[1]</value>
      <webElementGuid>3b51e0e7-20ed-4c65-a0e3-c0a27a3094e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Masukkan OTP'])[1]/following::button[1]</value>
      <webElementGuid>318fbbcd-b6e5-40e1-a1ac-f9b0a3140f8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Proses Dokumen'])[1]/preceding::button[2]</value>
      <webElementGuid>ed6b3914-fa40-41d2-b845-5a6cf05d2e74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='SMS']/parent::*</value>
      <webElementGuid>f4cb057e-6f16-4f77-b684-22fc36a05b1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/button</value>
      <webElementGuid>20bd72a1-ffcb-4532-9d23-d6b964a9e876</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btnotp' and @type = 'button' and (text() = '
                              	 SMS
                              ' or . = '
                              	 SMS
                              ')]</value>
      <webElementGuid>c3f367cf-b1cc-4b3d-b235-23b6f2be770f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
