<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>canvas_Proses_pdf-canvas</name>
   <tag></tag>
   <elementGuidId>c14e49a8-af83-43f3-96e6-c830d0c9641f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//canvas[@id='pdf-canvas']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#pdf-canvas</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>canvas</value>
      <webElementGuid>64c76642-1634-4eb1-b124-58f61c3c75bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pdf-canvas</value>
      <webElementGuid>2877038b-ab01-4d13-bfbc-999c8c9e4ae7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>3368</value>
      <webElementGuid>940fb5d5-0fbf-4867-986f-a69a988cc5d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>2380</value>
      <webElementGuid>d9790e30-46c1-4f0a-b6bf-8ad586fb93f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pdf-canvas&quot;)</value>
      <webElementGuid>3b5846c6-2fa4-45d4-83a1-3b1a97fe760f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//canvas[@id='pdf-canvas']</value>
      <webElementGuid>ce95135f-db0a-4ce4-9e70-04fa84ecaabd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pdf-contents']/canvas</value>
      <webElementGuid>ee2e15d7-865f-4a5d-9258-3fdbd9d5b0de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//canvas</value>
      <webElementGuid>02cd2b20-6a78-44ab-831b-d509af24dd7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//canvas[@id = 'pdf-canvas']</value>
      <webElementGuid>afbe5b6d-5ec8-4060-a77d-b127fe004342</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
