<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Dokumen gagal diproses</name>
   <tag></tag>
   <elementGuidId>328b44e3-c904-4959-bb8f-f3021e51398e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#text_mdl</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='text_mdl']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>62a3888d-94de-4556-bb3b-0e81a343cd29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal-body</value>
      <webElementGuid>a7b52b27-8da7-4e73-86ab-2f4a3901833a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text_mdl</value>
      <webElementGuid>4cf0bdc4-03a4-4a2b-9124-5946b04e2e28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dokumen gagal diproses</value>
      <webElementGuid>33c8f114-26f4-45e5-ab08-fbb204a8ef5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text_mdl&quot;)</value>
      <webElementGuid>1f75ce63-a989-45d6-9f07-ff7515225540</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='text_mdl']</value>
      <webElementGuid>7ab20a5c-225a-4b9f-a510-077ddb66b6c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='myModal']/div/div/div[2]</value>
      <webElementGuid>fd84ae77-3919-4e0b-9cd2-141895436f55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gagal'])[1]/following::div[1]</value>
      <webElementGuid>43140766-c903-495e-8956-3f5d9e43b1bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tutup'])[2]/following::div[5]</value>
      <webElementGuid>2e4ca908-eb4a-41dd-8e5d-35f261fa25f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tutup'])[3]/preceding::div[1]</value>
      <webElementGuid>dfd60075-7087-4579-986a-00af443b01f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[3]/preceding::div[2]</value>
      <webElementGuid>d09185af-0461-4805-8510-f1e0c03a6721</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Dokumen gagal diproses']/parent::*</value>
      <webElementGuid>d4cebe76-e4cc-4336-84cf-b06522c754bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[2]</value>
      <webElementGuid>83fb7721-6047-46eb-ad70-341c9da51039</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'text_mdl' and (text() = 'Dokumen gagal diproses' or . = 'Dokumen gagal diproses')]</value>
      <webElementGuid>8fb5384e-58d1-44c1-97ae-224d62fee290</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
