<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Kode OTP sudah dikirim sebanyak 3x. Sil_7b6418</name>
   <tag></tag>
   <elementGuidId>a61a825c-b862-43dc-b7cc-bb880922cb1c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#text_mdl</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Kode OTP sudah dikirim sebanyak 3x. Silakan coba kembali setelah 10 menit' or . = 'Kode OTP sudah dikirim sebanyak 3x. Silakan coba kembali setelah 10 menit')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='text_mdl']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>75dc0f61-eb11-4f8a-912e-c2cf62e3c95f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal-body</value>
      <webElementGuid>53a89063-b315-4921-a733-3ee40991e71e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text_mdl</value>
      <webElementGuid>a4d3155a-6a66-4a92-aecd-8a7f35ef5876</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kode OTP sudah dikirim sebanyak 3x. Silakan coba kembali setelah 10 menit</value>
      <webElementGuid>faf6d4d9-f70f-494d-9f4c-afee6d07a60d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text_mdl&quot;)</value>
      <webElementGuid>215f2529-5c5e-49d6-9658-7141115a845f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='text_mdl']</value>
      <webElementGuid>a536e0bb-b224-4841-9c22-fa2497d10bd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='myModal']/div/div/div[2]</value>
      <webElementGuid>90152b54-ad2d-456f-8435-7aa31693c3fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gagal'])[1]/following::div[1]</value>
      <webElementGuid>9c4200d5-562e-4242-86d1-49b7355c2591</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tutup'])[2]/following::div[5]</value>
      <webElementGuid>7ca063f4-457a-41a3-a524-9e0551b35bfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tutup'])[3]/preceding::div[1]</value>
      <webElementGuid>d575003a-421f-42d6-bfac-1f80fc860e25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[3]/preceding::div[2]</value>
      <webElementGuid>6df69c8f-55f2-49b7-834e-469bccfd74c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Kode OTP sudah dikirim sebanyak 3x.']/parent::*</value>
      <webElementGuid>e92398c1-291b-4dd4-bb91-c26957d1d528</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[2]</value>
      <webElementGuid>c29b6b0b-233c-4624-95c7-7f2b5d369d82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'text_mdl' and (text() = 'Kode OTP sudah dikirim sebanyak 3x. Silakan coba kembali setelah 10 menit' or . = 'Kode OTP sudah dikirim sebanyak 3x. Silakan coba kembali setelah 10 menit')]</value>
      <webElementGuid>f644451f-2e0d-4513-a315-92fd9d69b7ac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
