<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Please Wait_signpng0</name>
   <tag></tag>
   <elementGuidId>b32b9896-af84-4d37-acce-9f4fb7c62d6e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#signpng0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='signpng0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4e8352ae-ce80-4e6f-993f-78cc253ebe72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>37decef3-2438-49f6-a4b4-6d3601750ddf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>180</value>
      <webElementGuid>f5b826c4-bf92-423d-a2a3-c126360d482c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>80</value>
      <webElementGuid>fe1617c0-54d1-4f68-b82d-5827731fa891</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>sign</value>
      <webElementGuid>662b4537-9e5e-4242-8bed-0280211fca21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>signpng0</value>
      <webElementGuid>7f7216f4-ed4f-4364-9d9f-f24bede1f0d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>showttd('widget0','widget-0',0)</value>
      <webElementGuid>46312ea5-8235-45c9-ba47-f40396654934</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../images/signin.png</value>
      <webElementGuid>5d1e1b59-44f4-41b5-84ff-19aca72f2abf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;signpng0&quot;)</value>
      <webElementGuid>f6c4f907-1999-491c-8916-546736896658</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='signpng0']</value>
      <webElementGuid>67a6cad8-006b-4667-a18e-1f7bd21ee980</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='box']/input</value>
      <webElementGuid>c11a277e-ec88-4b40-9866-46786f174c14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>3a337e48-f3ed-411d-ad80-cb3f7ae0def2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'image' and @alt = 'sign' and @id = 'signpng0' and @src = '../images/signin.png']</value>
      <webElementGuid>43136160-c8d2-4b96-8590-587e361a90c0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
