<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Please Wait_signpng1</name>
   <tag></tag>
   <elementGuidId>3b69f521-b430-4325-94aa-ba00c6316368</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#signpng1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='signpng1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>01afed9c-a5ea-4185-915e-52e1b02bfc38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>109d095f-eb6d-4f59-8faf-74a250a6727d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>180</value>
      <webElementGuid>77d7db01-5dd1-4512-b5e6-6b3dd492f15f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>80</value>
      <webElementGuid>b6fd46b7-2617-47ae-a0cc-89dfdeeb4ccd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>sign</value>
      <webElementGuid>90a0de72-84f4-4b65-ba5f-c572ad9be395</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>signpng1</value>
      <webElementGuid>d177e768-9149-4b0c-9cab-0c574d12b778</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>showttd('widget1','widget-1',1)</value>
      <webElementGuid>a517e5c6-7866-4756-b3b7-42b3b6d31c6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../images/signhere.png</value>
      <webElementGuid>7cc90113-0cc6-4d28-9a64-27905550e6a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;signpng1&quot;)</value>
      <webElementGuid>8485fd0a-7d9a-4a70-9b5c-08e6cb363b8b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='signpng1']</value>
      <webElementGuid>3c8b08e0-7522-43fa-a4b0-7b1edba24782</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='box']/input)[2]</value>
      <webElementGuid>76f411e4-3bf3-47e5-8b67-fb00a6f6974e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/input</value>
      <webElementGuid>950451fc-4a9b-4114-9e74-c37fe6baf188</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'image' and @alt = 'sign' and @id = 'signpng1' and @src = '../images/signhere.png']</value>
      <webElementGuid>c7889749-afd2-4b5f-a892-dcad3cf8d535</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
