<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Iya</name>
   <tag></tag>
   <elementGuidId>0e3d5135-418f-41c4-ab15-5d760fdffa57</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='modreason']/div[2]/div/div/div/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>label.form-check-label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>d284b4a1-dc52-4da3-9f0d-65f386d502a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-label</value>
      <webElementGuid>13d171ee-2f64-421a-ae6c-4d2dd5878142</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>p1</value>
      <webElementGuid>8dba9974-9c87-4640-979d-aac44f393832</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Iya </value>
      <webElementGuid>0dd960f8-7bb1-4b57-8151-1d4d1affc822</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modreason&quot;)/div[@class=&quot;radio&quot;]/div[@class=&quot;row w-120 justify-content-center align-items-center mb-2&quot;]/div[@class=&quot;p-2&quot;]/div[@class=&quot;icheck-nephritis&quot;]/label[@class=&quot;form-check-label&quot;]</value>
      <webElementGuid>dc16230d-0112-4327-9e3e-749d8eec06d0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modreason']/div[2]/div/div/div/label</value>
      <webElementGuid>854b30fd-d5b3-4433-bf57-400b183e8363</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='telah membaca, memahami, dan menyetujui'])[1]/following::label[1]</value>
      <webElementGuid>7b9ba633-a0c7-43d1-b0ba-aa2d1fc983f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[7]/following::label[2]</value>
      <webElementGuid>3bae56ba-a8aa-4a8b-85d2-f6db691b5315</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tidak'])[1]/preceding::label[1]</value>
      <webElementGuid>864a3e9c-cf88-4725-b73b-a3404b27afa6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Masukkan OTP'])[1]/preceding::label[2]</value>
      <webElementGuid>60a382c6-8fc0-479a-8f9d-f226ac4604c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Iya']/parent::*</value>
      <webElementGuid>d4c1873a-b311-42db-aaee-2f8f9c5dafd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/div/label</value>
      <webElementGuid>0b0c51de-2299-4796-a4ba-a4b15a541298</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = ' Iya ' or . = ' Iya ')]</value>
      <webElementGuid>3eb2852d-0de4-4a57-bf90-f65aec384c87</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
